import type { LessonInput, SentenceInput } from "@/lib/models";

/**
 * The built-in deck: fifty curated sentences across five categories, written for this
 * app rather than taken from any course or other product.
 *
 * Ids are stable strings, so re-seeding matches existing rows instead of duplicating
 * them, and a learner's schedule survives an improved translation. **Never reuse an id
 * for different content** — the row is replaced in place, so the learner would keep the
 * progress of one sentence against the text of another.
 *
 * Travel and Custom are deliberately left empty. Custom is where the learner's own
 * imports land, and Travel keeps the Lessons screen's empty-category path exercised by
 * real data rather than only by a test.
 *
 * Content rules the whole deck follows:
 *
 * - **No symbols or notation in the English.** Every sentence is read aloud by
 *   Dictation and Speaking and typed back by hand, so parentheses, arrows and big-O
 *   notation would test transcription of punctuation rather than English.
 * - **`notes` is the Thai grammar explanation**, shown after grading. It says what the
 *   English does that Thai does not, which is where the mistakes actually come from.
 * - **`enAlternates` carries every natural rephrasing**, because the checker marks an
 *   unlisted-but-correct answer wrong, and being told you are wrong when you are not is
 *   the fastest way to stop trusting a trainer.
 */
export const SEED_VERSION = 4;

type SeedSentence = Omit<SentenceInput, "createdAt" | "updatedAt" | "source">;
type SeedLesson = Omit<LessonInput, "createdAt" | "updatedAt" | "source">;

export { SEED_VOCABULARY } from "./vocabulary";

export const SEED_SENTENCES: SeedSentence[] = [
  // ---------------------------------------------------------------- Daily conversation
  {
    id: "seed-sentence-0001",
    en: "Where are you going?",
    th: "คุณจะไปไหน",
    enAlternates: ["Where are you headed?"],
    thAlternates: ["คุณกำลังจะไปไหน"],
    transliteration: "khun ja pai nai",
    hint: "ไหน = where",
    notes: "ภาษาไทยวางคำถามไว้ท้ายประโยค แต่ภาษาอังกฤษขึ้นต้นด้วยคำถาม",
    exampleEn: "Where is he going?",
    exampleTh: "เขาจะไปไหน",
    tags: ["everyday", "questions"],
    category: "daily",
    level: "A1",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-where", "seed-vocab-go"],
  },
  {
    id: "seed-sentence-0002",
    en: "I am very hungry.",
    th: "ฉันหิวมาก",
    enAlternates: ["I'm very hungry."],
    transliteration: "chan hiu mak",
    hint: "มาก = very",
    notes: "ภาษาไทยไม่ต้องมี verb to be ตรงนี้ เพราะ หิว ทำหน้าที่เหมือนคำกริยาอยู่แล้ว",
    exampleEn: "I am very tired.",
    exampleTh: "ฉันเหนื่อยมาก",
    tags: ["everyday"],
    category: "daily",
    level: "A1",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-hungry", "seed-vocab-very"],
  },
  {
    id: "seed-sentence-0003",
    en: "I will call you tomorrow.",
    th: "พรุ่งนี้ฉันจะโทรหาคุณ",
    enAlternates: ["I'll call you tomorrow."],
    thAlternates: ["ฉันจะโทรหาคุณพรุ่งนี้"],
    transliteration: "phrung-nii chan ja tho ha khun",
    hint: "จะ บอกอนาคต",
    notes: "คำบอกเวลามักมาต้นประโยคในภาษาไทย แต่ภาษาอังกฤษนิยมไว้ท้ายประโยค",
    exampleEn: "I will email you tonight.",
    exampleTh: "คืนนี้ฉันจะส่งอีเมลหาคุณ",
    tags: ["everyday", "time"],
    category: "daily",
    level: "A2",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-tomorrow", "seed-vocab-call"],
  },
  {
    id: "seed-sentence-0007",
    en: "How much does this cost?",
    th: "อันนี้ราคาเท่าไหร่",
    enAlternates: ["How much is this?", "What does this cost?"],
    thAlternates: ["ราคาเท่าไหร่", "อันนี้เท่าไหร่"],
    transliteration: "an nii ra-kha thao rai",
    hint: "เท่าไหร่ = how much",
    notes: "cost เป็นคำกริยา จึงต้องใช้ does ช่วยในประโยคคำถาม ไม่ใช่ is เหมือนที่คนไทยมักเผลอพูด",
    exampleEn: "How much do these cost?",
    exampleTh: "พวกนี้ราคาเท่าไหร่",
    tags: ["everyday", "shopping"],
    category: "daily",
    level: "A1",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-how-much", "seed-vocab-cost"],
  },
  {
    id: "seed-sentence-0008",
    en: "Could you say that again, please?",
    th: "ช่วยพูดอีกครั้งได้ไหมครับ",
    enAlternates: ["Could you repeat that, please?", "Could you say that again?"],
    thAlternates: ["ช่วยพูดอีกทีได้ไหมครับ"],
    transliteration: "chuai phut iik khrang dai mai khrap",
    hint: "Could you ... ? = ช่วย ... ได้ไหม",
    notes: "หลัง Could you ใช้กริยารูปธรรมดาเสมอ ไม่เติม s และไม่เติม to นำหน้า",
    exampleEn: "Could you spell that, please?",
    exampleTh: "ช่วยสะกดให้หน่อยได้ไหมครับ",
    tags: ["everyday", "requests"],
    category: "daily",
    level: "A2",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-again", "seed-vocab-please"],
  },
  {
    id: "seed-sentence-0009",
    en: "Sorry, I didn't catch that.",
    th: "ขอโทษครับ ผมฟังไม่ทัน",
    enAlternates: ["Sorry, I did not catch that.", "Sorry, I didn't hear that."],
    thAlternates: ["ขอโทษครับ ผมไม่ได้ยิน"],
    transliteration: "kho thot khrap phom fang mai than",
    hint: "catch ที่นี่ = ฟังทัน",
    notes: "หลัง didn't ใช้กริยารูปธรรมดาเสมอ ไม่ใช่ didn't caught เพราะ did แบกความเป็นอดีตไว้แล้ว",
    exampleEn: "Sorry, I didn't catch your last point.",
    exampleTh: "ขอโทษครับ ประเด็นสุดท้ายผมฟังไม่ทัน",
    tags: ["everyday", "requests"],
    category: "daily",
    level: "A2",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-catch", "seed-vocab-sorry"],
  },
  {
    id: "seed-sentence-0010",
    en: "What time do you finish work?",
    th: "คุณเลิกงานกี่โมง",
    enAlternates: ["What time do you get off work?", "When do you finish work?"],
    thAlternates: ["คุณเลิกงานตอนกี่โมง"],
    transliteration: "khun loek ngan kii mong",
    hint: "กี่โมง = what time",
    notes: "คำถามเวลาขึ้นต้นด้วย What time แล้วตามด้วย do you ส่วนภาษาไทยวาง กี่โมง ไว้ท้ายประโยค",
    exampleEn: "What time do you start work?",
    exampleTh: "คุณเริ่มงานกี่โมง",
    tags: ["everyday", "time", "questions"],
    category: "daily",
    level: "A2",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-what-time", "seed-vocab-finish"],
  },
  {
    id: "seed-sentence-0011",
    en: "Let's meet in front of the station.",
    th: "เจอกันหน้าสถานีนะ",
    enAlternates: ["Let us meet in front of the station.", "Let's meet outside the station."],
    thAlternates: ["เจอกันที่หน้าสถานีนะ"],
    transliteration: "joe kan na sa-tha-nii na",
    hint: "หน้า = in front of",
    notes: "in front of ต้องมี of เสมอเมื่อตามด้วยคำนาม และต้องมี the นำหน้าสถานที่ที่ทั้งสองฝ่ายรู้จัก",
    exampleEn: "Let's meet in front of the office.",
    exampleTh: "เจอกันหน้าออฟฟิศนะ",
    tags: ["everyday", "directions"],
    category: "daily",
    level: "A2",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-meet", "seed-vocab-in-front-of"],
  },
  {
    id: "seed-sentence-0012",
    en: "It has been raining all morning.",
    th: "ฝนตกมาตลอดทั้งเช้า",
    enAlternates: ["It's been raining all morning.", "It has rained all morning."],
    thAlternates: ["ฝนตกทั้งเช้าเลย"],
    transliteration: "fon tok ma ta-lot thang chao",
    hint: "ตลอดทั้งเช้า = all morning",
    notes: "ประโยคเกี่ยวกับดินฟ้าอากาศต้องมีประธาน it เสมอ ทั้งที่ไม่มีผู้กระทำจริง ภาษาไทยไม่ต้องมี",
    exampleEn: "It has been raining since Tuesday.",
    exampleTh: "ฝนตกมาตั้งแต่วันอังคาร",
    tags: ["everyday", "weather"],
    category: "daily",
    level: "B1",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-rain", "seed-vocab-all"],
  },
  {
    id: "seed-sentence-0013",
    en: "I don't think I can make it tonight.",
    th: "คืนนี้ผมคงไปไม่ได้",
    enAlternates: ["I do not think I can make it tonight.", "I don't think I can come tonight."],
    thAlternates: ["คืนนี้ผมคงไม่ได้ไป"],
    transliteration: "khuen nii phom khong pai mai dai",
    hint: "make it = ไปร่วมได้",
    notes:
      "ภาษาอังกฤษนิยมปฏิเสธที่กริยาตัวแรก I don't think I can แทนที่จะพูดว่า I think I can't ซึ่งฟังแข็งกว่า",
    exampleEn: "I don't think I can make it on Friday.",
    exampleTh: "วันศุกร์ผมคงไปไม่ได้",
    tags: ["everyday", "invitations"],
    category: "daily",
    level: "B1",
    lessonIds: ["seed-lesson-daily"],
    vocabIds: ["seed-vocab-make-it", "seed-vocab-tonight"],
  },

  // ------------------------------------------------------------- Software engineering
  {
    id: "seed-sentence-0004",
    en: "Let's deploy this after the review.",
    th: "ดีพลอยตัวนี้หลังรีวิวเสร็จแล้วกัน",
    enAlternates: ["Let us deploy this after the review."],
    transliteration: "dii-phloi tua nii lang rii-wiu set laeo kan",
    hint: "Let's = ...กันเถอะ / ...กัน",
    notes: "Let's ย่อมาจาก Let us ใช้ชวนทำอะไรร่วมกัน ตามด้วยกริยารูปธรรมดาเสมอ",
    exampleEn: "Let's merge this tomorrow.",
    exampleTh: "พรุ่งนี้ค่อยเมิร์จตัวนี้กัน",
    tags: ["software", "review"],
    category: "software",
    level: "B1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-deploy", "seed-vocab-review"],
  },
  {
    id: "seed-sentence-0005",
    en: "Could you take another look at my pull request?",
    th: "ช่วยดูคำขอรวมโค้ดของผมอีกรอบได้ไหม",
    enAlternates: ["Could you review my pull request again?", "Could you look at my pull request again?"],
    thAlternates: ["รบกวนช่วยรีวิวคำขอรวมโค้ดของผมอีกครั้งได้ไหม"],
    transliteration: "chuai duu kham kho ruam khot khong phom iik rop dai mai",
    hint: "Could you ... ? = ช่วย ... ได้ไหม",
    notes: "Could you สุภาพกว่า Can you และใช้ขอความช่วยเหลือในที่ทำงานได้ปลอดภัยเสมอ",
    exampleEn: "Could you take another look at this test?",
    exampleTh: "ช่วยดูเทสต์ตัวนี้อีกรอบได้ไหม",
    tags: ["software", "requests"],
    category: "software",
    level: "B1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-pull-request", "seed-vocab-take-a-look"],
  },
  {
    id: "seed-sentence-0014",
    en: "The build is failing on the main branch.",
    th: "บิลด์บนสาขาหลักกำลังพังอยู่",
    enAlternates: ["The build is broken on the main branch.", "The build fails on the main branch."],
    thAlternates: ["บิลด์พังอยู่บนแบรนช์หลัก"],
    transliteration: "bin bon sa-kha lak kam-lang phang yu",
    hint: "is failing = กำลังพังอยู่ตอนนี้",
    notes: "รูป is failing บอกว่าเป็นอยู่ตอนนี้และยังไม่จบ ส่วน fails บอกว่าเป็นประจำ ซึ่งคนละความหมาย",
    exampleEn: "The build is failing on my branch too.",
    exampleTh: "บิลด์บนแบรนช์ผมก็พังเหมือนกัน",
    tags: ["software", "ci"],
    category: "software",
    level: "B1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-build", "seed-vocab-branch"],
  },
  {
    id: "seed-sentence-0015",
    en: "I have left a few comments on your pull request.",
    th: "ผมคอมเมนต์ไว้ในคำขอรวมโค้ดของคุณสองสามจุด",
    enAlternates: [
      "I've left a few comments on your pull request.",
      "I left a few comments on your pull request.",
    ],
    thAlternates: ["ผมฝากความเห็นไว้ในคำขอรวมโค้ดของคุณสองสามข้อ"],
    transliteration: "phom khom-men wai nai kham kho ruam khot khong khun song sam chut",
    hint: "leave a comment = ฝากความเห็นไว้",
    notes: "ภาษาอังกฤษใช้ leave กับ comment ไม่ใช่ put หรือ give และ a few ใช้กับคำนามนับได้เท่านั้น",
    exampleEn: "I have left a few notes in the document.",
    exampleTh: "ผมเขียนโน้ตไว้ในเอกสารสองสามจุด",
    tags: ["software", "review"],
    category: "software",
    level: "B1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-comment", "seed-vocab-a-few", "seed-vocab-pull-request"],
  },
  {
    id: "seed-sentence-0016",
    en: "This function does too many things at once.",
    th: "ฟังก์ชันนี้ทำหลายอย่างเกินไปในคราวเดียว",
    enAlternates: ["This function is doing too many things at once."],
    thAlternates: ["ฟังก์ชันนี้ทำงานหลายอย่างพร้อมกันเกินไป"],
    transliteration: "fang-chan nii tham lai yang koen pai nai khrao diao",
    hint: "too many = มากเกินไป (นับได้)",
    notes:
      "too many ใช้กับคำนามนับได้ ส่วน too much ใช้กับนับไม่ได้ คนไทยมักใช้สลับกันเพราะไทยใช้ เกินไป คำเดียว",
    exampleEn: "This class does too many things at once.",
    exampleTh: "คลาสนี้ทำหลายอย่างเกินไปในที่เดียว",
    tags: ["software", "review"],
    category: "software",
    level: "B1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-function", "seed-vocab-at-once"],
  },
  {
    id: "seed-sentence-0017",
    en: "Can you reproduce the bug on your machine?",
    th: "คุณทำให้บั๊กนี้เกิดซ้ำบนเครื่องคุณได้ไหม",
    enAlternates: ["Are you able to reproduce the bug on your machine?"],
    thAlternates: ["บั๊กนี้เกิดซ้ำบนเครื่องคุณไหม"],
    transliteration: "khun tham hai bak nii koet sam bon khrueang khun dai mai",
    hint: "reproduce = ทำให้เกิดซ้ำ",
    notes: "Can you ถามความสามารถ ส่วน Could you เป็นการขอร้อง ประโยคนี้ถามว่าทำได้ไหม จึงใช้ Can",
    exampleEn: "Can you reproduce it with the same input?",
    exampleTh: "ใช้อินพุตเดิมแล้วเกิดซ้ำไหม",
    tags: ["software", "debugging"],
    category: "software",
    level: "B1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-reproduce", "seed-vocab-machine"],
  },
  {
    id: "seed-sentence-0018",
    en: "We should add a test that covers this edge case.",
    th: "เราควรเพิ่มเทสต์ที่ครอบคลุมกรณีสุดขอบนี้",
    enAlternates: ["We should add a test for this edge case."],
    thAlternates: ["ควรเขียนเทสต์คลุมกรณีสุดขอบนี้ไว้ด้วย"],
    transliteration: "rao khuan phoem thet thii khrop khlum ko-ra-nii sut khop nii",
    hint: "cover = ครอบคลุม",
    notes:
      "that covers ขยายคำว่า test ให้ชัดว่าเป็นเทสต์แบบไหน และ covers ต้องเติม s ตามประธานเอกพจน์ a test",
    exampleEn: "We should add a test that covers empty input.",
    exampleTh: "เราควรเพิ่มเทสต์ที่ครอบคลุมกรณีอินพุตว่าง",
    tags: ["software", "testing"],
    category: "software",
    level: "B2",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-edge-case", "seed-vocab-cover", "seed-vocab-add"],
  },
  {
    id: "seed-sentence-0019",
    en: "I rolled back the release because latency spiked.",
    th: "ผมย้อนรีลีสกลับเพราะค่าหน่วงพุ่งขึ้น",
    enAlternates: ["I rolled the release back because latency spiked."],
    thAlternates: ["ผมถอนรีลีสกลับเพราะเวลาตอบสนองพุ่งขึ้น"],
    transliteration: "phom yon rii-lit klap phro kha nuang phung khuen",
    hint: "roll back = ย้อนกลับเวอร์ชัน",
    notes: "because ตามด้วยประโยคเต็มที่มีประธานและกริยา ส่วน because of ตามด้วยคำนามเท่านั้น",
    exampleEn: "We rolled back the change because errors spiked.",
    exampleTh: "เราย้อนการแก้กลับเพราะเออเรอร์พุ่งขึ้น",
    tags: ["software", "release"],
    category: "software",
    level: "B2",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-roll-back", "seed-vocab-spike"],
  },
  {
    id: "seed-sentence-0020",
    en: "The migration has to be backwards compatible.",
    th: "การย้ายโครงสร้างข้อมูลต้องเข้ากันได้กับของเดิม",
    enAlternates: [
      "The migration must be backwards compatible.",
      "The migration has to be backward compatible.",
    ],
    thAlternates: ["migration ต้องไม่ทำให้ของเดิมพัง"],
    transliteration: "kan yai khrong sang kho-mun tong khao kan dai kap khong doem",
    hint: "has to = ต้อง",
    notes:
      "has to และ must แปลว่าต้องเหมือนกัน แต่ has to ใช้กับกฎที่มาจากภายนอก ส่วน must ฟังเหมือนผู้พูดเป็นคนกำหนด",
    exampleEn: "The change has to be reversible.",
    exampleTh: "การแก้นี้ต้องย้อนกลับได้",
    tags: ["software", "data"],
    category: "software",
    level: "B2",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-migration", "seed-vocab-backwards-compatible"],
  },
  {
    id: "seed-sentence-0021",
    en: "Let me walk you through the architecture.",
    th: "เดี๋ยวผมพาไล่ดูสถาปัตยกรรมทีละส่วน",
    enAlternates: ["Let me take you through the architecture."],
    thAlternates: ["ขออธิบายสถาปัตยกรรมให้ฟังทีละส่วนนะครับ"],
    transliteration: "diao phom pha lai duu sa-tha-pat-ta-ya-kam thii la suan",
    hint: "walk someone through = พาไล่ดูทีละขั้น",
    notes: "Let me ตามด้วยกริยารูปธรรมดา และผู้ฟังต้องอยู่กลางวลี walk you through ไม่ใช่ท้ายประโยค",
    exampleEn: "Let me walk you through the error log.",
    exampleTh: "เดี๋ยวผมพาไล่ดูล็อกเออเรอร์",
    tags: ["software", "explaining"],
    category: "software",
    level: "B2",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-walk-through", "seed-vocab-architecture"],
  },
  {
    id: "seed-sentence-0022",
    en: "We are trading readability for performance here.",
    th: "ตรงนี้เรากำลังแลกความอ่านง่ายกับประสิทธิภาพ",
    enAlternates: ["We're trading readability for performance here."],
    thAlternates: ["ตรงนี้เรายอมให้โค้ดอ่านยากขึ้นเพื่อให้เร็วขึ้น"],
    transliteration: "trong nii rao kam-lang laek khwam an ngai kap pra-sit-thi-phap",
    hint: "trade A for B = แลก A กับ B",
    notes:
      "โครงสร้าง trade A for B สิ่งที่ยอมเสียมาก่อน สิ่งที่ได้มาอยู่หลัง for สลับที่แล้วความหมายกลับด้าน",
    exampleEn: "We are trading flexibility for simplicity.",
    exampleTh: "เรากำลังแลกความยืดหยุ่นกับความเรียบง่าย",
    tags: ["software", "design"],
    category: "software",
    level: "C1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-trade", "seed-vocab-readability"],
  },
  {
    id: "seed-sentence-0023",
    en: "The root cause was a race condition in the cache.",
    th: "สาเหตุที่แท้จริงคือภาวะแย่งกันทำงานในแคช",
    enAlternates: ["The root cause turned out to be a race condition in the cache."],
    thAlternates: ["ต้นตอจริงคือ race condition ในแคช"],
    transliteration: "sa-het thii thae ching khue pha-wa yaeng kan tham ngan nai khaet",
    hint: "root cause = สาเหตุที่แท้จริง",
    notes: "ภาษาอังกฤษต้องมี a หรือ the นำหน้าคำนามนับได้เสมอ ภาษาไทยไม่มีคำนำหน้านาม จึงมักถูกลืม",
    exampleEn: "The root cause was a missing index.",
    exampleTh: "สาเหตุที่แท้จริงคือลืมสร้างดัชนี",
    tags: ["software", "debugging"],
    category: "software",
    level: "C1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-root-cause", "seed-vocab-race-condition"],
  },
  {
    id: "seed-sentence-0024",
    en: "Could you rebase onto main before I merge?",
    th: "ช่วยรีเบสไปบนสาขาหลักก่อนผมเมิร์จได้ไหม",
    enAlternates: ["Could you rebase on main before I merge?"],
    thAlternates: ["รบกวนรีเบสขึ้น main ก่อนผมเมิร์จนะครับ"],
    transliteration: "chuai rii-bet pai bon sa-kha lak kon phom moet dai mai",
    hint: "rebase onto = รีเบสไปบน",
    notes: "หลัง before ใช้รูปปัจจุบัน I merge เพื่อพูดถึงอนาคต ไม่ใช้ will ซึ่งเป็นจุดที่คนไทยมักเผลอเติม",
    exampleEn: "Could you rebase before the release?",
    exampleTh: "ช่วยรีเบสก่อนปล่อยรีลีสได้ไหม",
    tags: ["software", "git"],
    category: "software",
    level: "B2",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-rebase", "seed-vocab-merge"],
  },
  {
    id: "seed-sentence-0025",
    en: "This change is bigger than it needs to be.",
    th: "การแก้ครั้งนี้ใหญ่เกินความจำเป็น",
    enAlternates: ["This change is larger than it needs to be."],
    thAlternates: ["การแก้รอบนี้ใหญ่กว่าที่จำเป็น"],
    transliteration: "kan kae khrang nii yai koen khwam cham-pen",
    hint: "bigger than it needs to be = ใหญ่เกินจำเป็น",
    notes: "วลี than it needs to be เป็นคำติที่สุภาพ เพราะติที่ขนาดของงาน ไม่ได้ติที่ตัวคนเขียน",
    exampleEn: "This meeting is longer than it needs to be.",
    exampleTh: "ประชุมนี้ยาวเกินความจำเป็น",
    tags: ["software", "review"],
    category: "software",
    level: "B2",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-change", "seed-vocab-need"],
  },
  {
    id: "seed-sentence-0026",
    en: "I would rather ship it behind a feature flag.",
    th: "ผมอยากปล่อยขึ้นไปก่อนโดยซ่อนไว้หลังสวิตช์ฟีเจอร์",
    enAlternates: ["I'd rather ship it behind a feature flag."],
    thAlternates: ["ผมขอปล่อยขึ้นระบบแต่ยังไม่เปิดให้ผู้ใช้เห็น"],
    transliteration: "phom yak ploi khuen pai kon doi son wai lang sa-wit fi-choe",
    hint: "would rather = อยาก ... มากกว่า",
    notes: "หลัง would rather ใช้กริยารูปธรรมดาโดยไม่มี to ต่างจาก would like to ที่ต้องมี to",
    exampleEn: "I would rather wait until Monday.",
    exampleTh: "ผมขอรอถึงวันจันทร์ดีกว่า",
    tags: ["software", "release"],
    category: "software",
    level: "C1",
    lessonIds: ["seed-lesson-software"],
    vocabIds: ["seed-vocab-ship", "seed-vocab-feature-flag"],
  },

  // ------------------------------------------------------------------------- Meetings
  {
    id: "seed-sentence-0006",
    en: "I don't have any blockers today.",
    th: "วันนี้ผมไม่มีอะไรติดขัด",
    enAlternates: ["I have no blockers today.", "I do not have any blockers today."],
    transliteration: "wan nii phom mai mii arai tit khat",
    hint: "don't have any = ไม่มี...เลย",
    notes: "ประโยคปฏิเสธใช้ any คู่กับ don't ส่วน no ใช้กับประโยคบอกเล่า เช่น I have no blockers",
    exampleEn: "I don't have any updates today.",
    exampleTh: "วันนี้ผมไม่มีอะไรอัปเดต",
    tags: ["meetings", "standup"],
    category: "meetings",
    level: "A2",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-blocker", "seed-vocab-today"],
  },
  {
    id: "seed-sentence-0027",
    en: "Yesterday I finished the login screen.",
    th: "เมื่อวานผมทำหน้าล็อกอินเสร็จ",
    enAlternates: ["I finished the login screen yesterday."],
    thAlternates: ["เมื่อวานผมทำหน้าเข้าสู่ระบบเสร็จแล้ว"],
    transliteration: "muea wan phom tham na lok-in set",
    hint: "finished = ทำเสร็จแล้ว (อดีต)",
    notes:
      "yesterday บังคับให้กริยาเป็นรูปอดีต finished ภาษาไทยใช้คำว่า เมื่อวาน อย่างเดียวโดยไม่เปลี่ยนรูปกริยา",
    exampleEn: "Yesterday I finished the search filter.",
    exampleTh: "เมื่อวานผมทำตัวกรองการค้นหาเสร็จ",
    tags: ["meetings", "standup"],
    category: "meetings",
    level: "A2",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-yesterday", "seed-vocab-finish"],
  },
  {
    id: "seed-sentence-0028",
    en: "Could we park that and come back to it later?",
    th: "เรื่องนั้นขอพักไว้ก่อนแล้วค่อยกลับมาคุยได้ไหม",
    enAlternates: ["Can we park that and come back to it later?"],
    thAlternates: ["ขอเก็บเรื่องนั้นไว้คุยทีหลังได้ไหมครับ"],
    transliteration: "rueang nan kho phak wai kon laeo khoi klap ma khui dai mai",
    hint: "park = พักเรื่องไว้ก่อน",
    notes: "come back to ต้องมี to เสมอเมื่อมีสิ่งที่จะกลับไปคุย ถ้าตัด to ออกจะกลายเป็นกลับมาที่สถานที่",
    exampleEn: "Could we park the naming question for now?",
    exampleTh: "เรื่องตั้งชื่อขอพักไว้ก่อนได้ไหม",
    tags: ["meetings", "facilitation"],
    category: "meetings",
    level: "B2",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-park", "seed-vocab-come-back-to"],
  },
  {
    id: "seed-sentence-0029",
    en: "I would like to add one thing to the agenda.",
    th: "ผมขอเพิ่มอีกเรื่องหนึ่งในวาระการประชุม",
    enAlternates: ["I'd like to add one thing to the agenda.", "I want to add one thing to the agenda."],
    thAlternates: ["ขอเพิ่มหัวข้ออีกหนึ่งเรื่องในวาระครับ"],
    transliteration: "phom kho phoem iik rueang nueng nai wa-ra kan pra-chum",
    hint: "would like to = ขอ / อยาก",
    notes: "I would like to สุภาพกว่า I want to มาก และต้องมี to ตามด้วยกริยารูปธรรมดาเสมอ",
    exampleEn: "I would like to add one more item.",
    exampleTh: "ผมขอเพิ่มอีกหนึ่งหัวข้อ",
    tags: ["meetings"],
    category: "meetings",
    level: "B1",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-agenda", "seed-vocab-add"],
  },
  {
    id: "seed-sentence-0030",
    en: "Sorry, I think you are on mute.",
    th: "ขอโทษครับ ผมว่าคุณปิดไมค์อยู่",
    enAlternates: ["Sorry, I think you're on mute.", "Sorry, you are on mute."],
    thAlternates: ["ขอโทษครับ ไมค์คุณปิดอยู่"],
    transliteration: "kho thot khrap phom wa khun pit mai yu",
    hint: "on mute = ปิดไมค์อยู่",
    notes: "ขึ้นต้นด้วย I think ทำให้ฟังนุ่มลง เป็นวิธีบอกคนอื่นว่าผิดพลาดโดยไม่ทำให้เสียหน้า",
    exampleEn: "Sorry, I think your camera is off.",
    exampleTh: "ขอโทษครับ ผมว่ากล้องคุณปิดอยู่",
    tags: ["meetings", "remote"],
    category: "meetings",
    level: "A2",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-mute", "seed-vocab-sorry"],
  },
  {
    id: "seed-sentence-0031",
    en: "To summarise, we agreed on three things.",
    th: "สรุปคือเราตกลงกันไว้สามเรื่อง",
    enAlternates: ["To summarize, we agreed on three things.", "In summary, we agreed on three things."],
    thAlternates: ["สรุปแล้วเราตกลงกันสามข้อ"],
    transliteration: "sa-rup khue rao tok long kan wai sam rueang",
    hint: "To summarise = สรุปคือ",
    notes: "agree ต้องตามด้วย on เมื่อพูดถึงสิ่งที่ตกลงกัน ส่วน agree with ใช้กับคน ไม่ใช่กับข้อสรุป",
    exampleEn: "To summarise, we are moving the deadline.",
    exampleTh: "สรุปคือเราจะเลื่อนกำหนดส่ง",
    tags: ["meetings"],
    category: "meetings",
    level: "B1",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-summarise", "seed-vocab-agree"],
  },
  {
    id: "seed-sentence-0032",
    en: "I see it differently, and here is why.",
    th: "ผมมองต่างออกไป และนี่คือเหตุผล",
    enAlternates: ["I see it differently, and here's why.", "I see this differently, and here is why."],
    thAlternates: ["ผมเห็นต่างครับ ขออธิบายเหตุผล"],
    transliteration: "phom mong tang ok pai lae nii khue het phon",
    hint: "see it differently = มองต่าง",
    notes:
      "เป็นการค้านที่สุภาพ เพราะพูดถึงมุมมองของตัวเอง ไม่ได้บอกว่าอีกฝ่ายผิด ต่างจาก You are wrong ที่ฟังแรงมาก",
    exampleEn: "I see the trade off differently.",
    exampleTh: "ผมมองเรื่องการแลกได้แลกเสียต่างออกไป",
    tags: ["meetings", "disagreeing"],
    category: "meetings",
    level: "B2",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-differently", "seed-vocab-see"],
  },
  {
    id: "seed-sentence-0033",
    en: "Can we push this meeting to Thursday?",
    th: "เลื่อนประชุมนี้ไปวันพฤหัสได้ไหม",
    enAlternates: ["Could we push this meeting to Thursday?", "Can we move this meeting to Thursday?"],
    thAlternates: ["ขอเลื่อนประชุมไปวันพฤหัสได้ไหมครับ"],
    transliteration: "luean pra-chum nii pai wan pha-rue-hat dai mai",
    hint: "push ... to = เลื่อนไปเป็น",
    notes: "push ที่นี่แปลว่าเลื่อนเวลา ไม่ใช่ผลัก และใช้ to กับวันที่จะเลื่อนไป ไม่ใช่ until",
    exampleEn: "Can we push the demo to next week?",
    exampleTh: "เลื่อนเดโมไปอาทิตย์หน้าได้ไหม",
    tags: ["meetings", "scheduling"],
    category: "meetings",
    level: "B1",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-push", "seed-vocab-meeting"],
  },
  {
    id: "seed-sentence-0034",
    en: "Who is taking this one?",
    th: "เรื่องนี้ใครรับไปทำ",
    enAlternates: ["Who's taking this one?", "Who is picking this one up?"],
    thAlternates: ["อันนี้ใครรับไปครับ"],
    transliteration: "rueang nii khrai rap pai tham",
    hint: "take = รับไปทำ",
    notes: "who เป็นประธานอยู่แล้ว จึงไม่ต้องมี does ช่วย ใช้ Who is taking ตรง ๆ ไม่ใช่ Who does take",
    exampleEn: "Who is taking the on call this week?",
    exampleTh: "อาทิตย์นี้ใครรับเวรดูระบบ",
    tags: ["meetings", "work"],
    category: "meetings",
    level: "B1",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-take", "seed-vocab-one"],
  },
  {
    id: "seed-sentence-0035",
    en: "Let's take that offline.",
    th: "เรื่องนั้นไปคุยกันต่อนอกที่ประชุมนะ",
    enAlternates: ["Let us take that offline.", "Let's discuss that offline."],
    thAlternates: ["ขอยกเรื่องนั้นไปคุยข้างนอกนะครับ"],
    transliteration: "rueang nan pai khui kan to nok thii pra-chum na",
    hint: "take offline = ยกไปคุยนอกวง",
    notes:
      "เป็นสำนวน ไม่ได้เกี่ยวกับอินเทอร์เน็ต หมายถึงยกเรื่องไปคุยกันเองหลังประชุมเพื่อไม่ให้เสียเวลาคนอื่น",
    exampleEn: "Let's take the schema debate offline.",
    exampleTh: "เรื่องเถียงสกีมาไปคุยกันต่อข้างนอกนะ",
    tags: ["meetings"],
    category: "meetings",
    level: "B2",
    lessonIds: ["seed-lesson-meetings"],
    vocabIds: ["seed-vocab-offline", "seed-vocab-take"],
  },

  // -------------------------------------------------------------- Technical interviews
  {
    id: "seed-sentence-0036",
    en: "Let me make sure I understand the problem.",
    th: "ขอผมทบทวนโจทย์ให้แน่ใจก่อนนะครับ",
    enAlternates: ["Let me make sure I understand the question."],
    thAlternates: ["ขอทวนโจทย์ให้แน่ใจก่อนครับ"],
    transliteration: "kho phom thop thuan chot hai nae chai kon na khrap",
    hint: "make sure = ทำให้แน่ใจ",
    notes: "หลัง make sure ตามด้วยประโยคเต็ม ไม่ใช่คำนาม และไม่ต้องมี that ก็ได้ในภาษาพูด",
    exampleEn: "Let me make sure I have the constraints right.",
    exampleTh: "ขอผมเช็กข้อจำกัดให้ชัดก่อนนะครับ",
    tags: ["interviews"],
    category: "interviews",
    level: "B1",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-make-sure", "seed-vocab-understand"],
  },
  {
    id: "seed-sentence-0037",
    en: "Can I assume the input is already sorted?",
    th: "ผมสมมติว่าอินพุตเรียงมาแล้วได้ไหมครับ",
    enAlternates: ["May I assume the input is already sorted?", "Can I assume the input is sorted?"],
    thAlternates: ["ขอสมมติว่าข้อมูลเข้าเรียงมาแล้วได้ไหมครับ"],
    transliteration: "phom som-mut wa in-phut riang ma laeo dai mai khrap",
    hint: "assume = สมมติ",
    notes: "already วางระหว่างกริยาช่วยกับกริยาหลัก คือ is already sorted ไม่ใช่ท้ายประโยคแบบภาษาไทย",
    exampleEn: "Can I assume the list fits in memory?",
    exampleTh: "ผมสมมติว่าลิสต์ใส่ในหน่วยความจำได้หมดไหมครับ",
    tags: ["interviews"],
    category: "interviews",
    level: "B1",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-assume", "seed-vocab-input"],
  },
  {
    id: "seed-sentence-0038",
    en: "My first approach would be a brute force solution.",
    th: "วิธีแรกที่ผมนึกถึงคือการไล่ลองทุกความเป็นไปได้",
    enAlternates: ["My first approach would be brute force."],
    thAlternates: ["แนวทางแรกของผมคือลองทุกกรณีก่อน"],
    transliteration: "wi-thii raek thii phom nuek thueng khue kan lai long thuk khwam pen pai dai",
    hint: "approach = วิธีการ",
    notes: "would be ทำให้ฟังเป็นข้อเสนอที่ยังเปิดรับความเห็น ต่างจาก is ที่ฟังเหมือนตัดสินใจไปแล้ว",
    exampleEn: "My first approach would be a simple loop.",
    exampleTh: "วิธีแรกของผมคือวนลูปธรรมดา",
    tags: ["interviews", "algorithms"],
    category: "interviews",
    level: "B2",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-approach", "seed-vocab-brute-force"],
  },
  {
    id: "seed-sentence-0039",
    en: "That approach runs in linear time.",
    th: "วิธีนั้นใช้เวลาแบบเชิงเส้น",
    enAlternates: ["That approach runs in linear time complexity."],
    thAlternates: ["แนวทางนั้นใช้เวลาเชิงเส้น"],
    transliteration: "wi-thii nan chai we-la baep choeng sen",
    hint: "run in ... time = ใช้เวลา...",
    notes: "ใช้ in กับความซับซ้อนของเวลาเสมอ ไม่ใช่ at หรือ with และ time ตรงนี้นับไม่ได้ จึงไม่เติม s",
    exampleEn: "The lookup runs in constant time.",
    exampleTh: "การค้นหานี้ใช้เวลาคงที่",
    tags: ["interviews", "algorithms"],
    category: "interviews",
    level: "B2",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-run", "seed-vocab-linear", "seed-vocab-approach"],
  },
  {
    id: "seed-sentence-0040",
    en: "I can trade memory for speed by using a hash map.",
    th: "ผมแลกหน่วยความจำกับความเร็วได้ด้วยการใช้แฮชแมป",
    enAlternates: ["I can trade memory for speed with a hash map."],
    thAlternates: ["ผมยอมใช้หน่วยความจำเพิ่มเพื่อให้เร็วขึ้นด้วยแฮชแมป"],
    transliteration: "phom laek nuai khwam cham kap khwam reo dai duai kan chai haet-maep",
    hint: "trade A for B = แลก A กับ B",
    notes: "หลัง by ต้องใช้กริยาเติม ing เสมอ คือ by using ไม่ใช่ by use ซึ่งเป็นจุดที่พลาดกันบ่อย",
    exampleEn: "We can trade accuracy for speed here.",
    exampleTh: "ตรงนี้เราแลกความแม่นยำกับความเร็วได้",
    tags: ["interviews", "algorithms"],
    category: "interviews",
    level: "C1",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-trade", "seed-vocab-hash-map", "seed-vocab-memory"],
  },
  {
    id: "seed-sentence-0041",
    en: "Let me walk through an example step by step.",
    th: "ขอผมไล่ตัวอย่างทีละขั้นนะครับ",
    enAlternates: ["Let me go through an example step by step."],
    thAlternates: ["ขอยกตัวอย่างแล้วไล่ทีละขั้นนะครับ"],
    transliteration: "kho phom lai tua yang thii la khan na khrap",
    hint: "step by step = ทีละขั้น",
    notes: "step by step ไม่ต้องมี the คั่น และไม่เติม s แม้จะหมายถึงหลายขั้นก็ตาม",
    exampleEn: "Let me walk through the first case step by step.",
    exampleTh: "ขอไล่กรณีแรกทีละขั้นนะครับ",
    tags: ["interviews", "explaining"],
    category: "interviews",
    level: "B1",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-walk-through", "seed-vocab-step-by-step", "seed-vocab-example"],
  },
  {
    id: "seed-sentence-0042",
    en: "I would like to handle the empty input case first.",
    th: "ผมขอจัดการกรณีอินพุตว่างก่อนครับ",
    enAlternates: ["I'd like to handle the empty input case first."],
    thAlternates: ["ขอเริ่มจากกรณีข้อมูลเข้าว่างก่อนนะครับ"],
    transliteration: "phom kho chat kan ko-ra-nii in-phut wang kon khrap",
    hint: "handle = จัดการ / รองรับ",
    notes: "first วางท้ายประโยคเมื่อบอกลำดับการทำงาน ส่วน at first แปลว่าตอนแรก ซึ่งคนละความหมาย",
    exampleEn: "I would like to handle the error case first.",
    exampleTh: "ผมขอจัดการกรณีที่ผิดพลาดก่อนครับ",
    tags: ["interviews", "software"],
    category: "interviews",
    level: "B2",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-handle", "seed-vocab-empty", "seed-vocab-input"],
  },
  {
    id: "seed-sentence-0043",
    en: "Could you give me a hint? I am stuck.",
    th: "ขอคำใบ้หน่อยได้ไหมครับ ผมติดอยู่",
    enAlternates: ["Could you give me a hint? I'm stuck."],
    thAlternates: ["รบกวนขอคำใบ้หน่อยครับ ผมคิดต่อไม่ออก"],
    transliteration: "kho kham bai noi dai mai khrap phom tit yu",
    hint: "stuck = ติด ไปต่อไม่ได้",
    notes:
      "stuck เป็นคำคุณศัพท์ จึงต้องใช้คู่กับ be เสมอ พูดว่า I stuck จะกลายเป็นอดีตของ stick ที่แปลว่าติดกาว",
    exampleEn: "Could you give me a hint about the data structure?",
    exampleTh: "ขอคำใบ้เรื่องโครงสร้างข้อมูลหน่อยได้ไหมครับ",
    tags: ["interviews"],
    category: "interviews",
    level: "B1",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-hint", "seed-vocab-stuck"],
  },
  {
    id: "seed-sentence-0044",
    en: "I have worked mostly on backend systems.",
    th: "ผมทำงานกับระบบฝั่งหลังบ้านเป็นหลัก",
    enAlternates: ["I've worked mostly on backend systems.", "I have mostly worked on backend systems."],
    thAlternates: ["ผมทำระบบหลังบ้านมาเป็นหลัก"],
    transliteration: "phom tham ngan kap ra-bop fang lang ban pen lak",
    hint: "mostly = เป็นหลัก",
    notes: "ใช้ have worked เพราะยังทำอยู่ถึงปัจจุบัน ถ้าใช้ worked เฉย ๆ จะหมายถึงจบไปแล้วและไม่ทำอีก",
    exampleEn: "I have worked mostly on payment systems.",
    exampleTh: "ผมทำระบบชำระเงินมาเป็นหลัก",
    tags: ["interviews", "experience"],
    category: "interviews",
    level: "B1",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-backend", "seed-vocab-mostly"],
  },
  {
    id: "seed-sentence-0045",
    en: "What does the team's day to day look like?",
    th: "งานประจำวันของทีมเป็นอย่างไรบ้างครับ",
    enAlternates: ["What does the team's day to day look like?", "What is the team's day to day like?"],
    thAlternates: ["ปกติทีมทำอะไรกันบ้างในแต่ละวันครับ"],
    transliteration: "ngan pra-cham wan khong thim pen yang rai bang khrap",
    hint: "What does ... look like? = ...เป็นอย่างไร",
    notes: "ในคำถามนี้ look like ต้องอยู่ท้ายประโยคเสมอ และใช้ does ช่วยเพราะประธานเป็นเอกพจน์",
    exampleEn: "What does the review process look like?",
    exampleTh: "ขั้นตอนการรีวิวเป็นอย่างไรบ้างครับ",
    tags: ["interviews", "questions"],
    category: "interviews",
    level: "B2",
    lessonIds: ["seed-lesson-interviews"],
    vocabIds: ["seed-vocab-day-to-day", "seed-vocab-team", "seed-vocab-take-a-look"],
  },

  // ----------------------------------------------------------------- Workplace English
  {
    id: "seed-sentence-0046",
    en: "I would like to take Friday off.",
    th: "ผมขอลาวันศุกร์ครับ",
    enAlternates: ["I'd like to take Friday off.", "I would like to take Friday off, please."],
    thAlternates: ["ผมขอหยุดวันศุกร์ครับ"],
    transliteration: "phom kho la wan suk khrap",
    hint: "take a day off = ลาหยุด",
    notes: "วันที่จะลาต้องแทรกอยู่กลางวลี คือ take Friday off เขียน take off Friday จะฟังผิดทันที",
    exampleEn: "I would like to take Monday off.",
    exampleTh: "ผมขอลาวันจันทร์ครับ",
    tags: ["workplace", "leave"],
    category: "workplace",
    level: "A2",
    lessonIds: ["seed-lesson-workplace"],
    vocabIds: ["seed-vocab-take-off", "seed-vocab-friday"],
  },
  {
    id: "seed-sentence-0047",
    en: "I am attaching the report to this email.",
    th: "ผมแนบรายงานมากับอีเมลฉบับนี้",
    enAlternates: ["I'm attaching the report to this email.", "I have attached the report to this email."],
    thAlternates: ["แนบรายงานมาให้ในอีเมลนี้แล้วครับ"],
    transliteration: "phom naep rai ngan ma kap ii-men cha-bap nii",
    hint: "attach A to B = แนบ A ไปกับ B",
    notes: "attach ใช้กับ to ไม่ใช่ with และรูป am attaching บอกว่ากำลังทำในอีเมลฉบับนี้เอง",
    exampleEn: "I am attaching the invoice to this email.",
    exampleTh: "ผมแนบใบแจ้งหนี้มากับอีเมลนี้",
    tags: ["workplace", "email"],
    category: "workplace",
    level: "B1",
    lessonIds: ["seed-lesson-workplace"],
    vocabIds: ["seed-vocab-attach", "seed-vocab-report"],
  },
  {
    id: "seed-sentence-0048",
    en: "Thanks for the heads up.",
    th: "ขอบคุณที่บอกล่วงหน้านะครับ",
    enAlternates: ["Thanks for the heads-up.", "Thank you for the heads up."],
    thAlternates: ["ขอบคุณที่เตือนล่วงหน้าครับ"],
    transliteration: "khop khun thii bok luang na na khrap",
    hint: "heads up = การบอกล่วงหน้า",
    notes: "heads up เป็นคำนามในวลีนี้ จึงต้องมี the นำหน้า และตามหลัง for เสมอ",
    exampleEn: "Thanks for the heads up about the outage.",
    exampleTh: "ขอบคุณที่บอกล่วงหน้าเรื่องระบบล่มนะครับ",
    tags: ["workplace"],
    category: "workplace",
    level: "B1",
    lessonIds: ["seed-lesson-workplace"],
    vocabIds: ["seed-vocab-heads-up", "seed-vocab-thanks"],
  },
  {
    id: "seed-sentence-0049",
    en: "I will be working from home tomorrow.",
    th: "พรุ่งนี้ผมจะทำงานที่บ้านครับ",
    enAlternates: ["I'll be working from home tomorrow.", "I am working from home tomorrow."],
    thAlternates: ["พรุ่งนี้ผมทำงานที่บ้านนะครับ"],
    transliteration: "phrung-nii phom ja tham ngan thii ban khrap",
    hint: "work from home = ทำงานที่บ้าน",
    notes: "ใช้ from ไม่ใช่ at และ home ไม่ต้องมี the นำหน้า ต่างจากสถานที่อื่นอย่าง the office",
    exampleEn: "I will be working from home on Friday.",
    exampleTh: "วันศุกร์ผมจะทำงานที่บ้านครับ",
    tags: ["workplace", "remote"],
    category: "workplace",
    level: "A2",
    lessonIds: ["seed-lesson-workplace"],
    vocabIds: ["seed-vocab-work-from-home", "seed-vocab-tomorrow"],
  },
  {
    id: "seed-sentence-0050",
    en: "Sorry for the slow reply. I was away last week.",
    th: "ขอโทษที่ตอบช้าครับ อาทิตย์ที่แล้วผมไม่อยู่",
    enAlternates: [
      "Sorry for the slow reply, I was away last week.",
      "Apologies for the slow reply. I was away last week.",
    ],
    thAlternates: ["ขอโทษที่ตอบกลับช้านะครับ อาทิตย์ที่แล้วผมลาไป"],
    transliteration: "kho thot thii top cha khrap a-thit thii laeo phom mai yu",
    hint: "sorry for + คำนาม",
    notes: "หลัง sorry for ตามด้วยคำนามหรือกริยาเติม ing เท่านั้น จะพูดว่า sorry for reply late ไม่ได้",
    exampleEn: "Sorry for the late reply. I was on leave.",
    exampleTh: "ขอโทษที่ตอบช้าครับ ผมลาพักร้อนอยู่",
    tags: ["workplace", "email"],
    category: "workplace",
    level: "B1",
    lessonIds: ["seed-lesson-workplace"],
    vocabIds: ["seed-vocab-reply", "seed-vocab-away", "seed-vocab-sorry"],
  },
];

/**
 * One lesson per stocked category, in teaching order rather than id order.
 *
 * `seed-lesson-daily` keeps the id the first placeholder lesson had, so an existing
 * database is updated in place instead of being left with an orphan row.
 */
export const SEED_LESSONS: SeedLesson[] = [
  {
    id: "seed-lesson-daily",
    title: "Daily Conversation",
    titleTh: "บทสนทนาประจำวัน",
    description: "Asking, arranging and turning things down, in the words people actually use.",
    tags: ["starter", "everyday"],
    level: "A1",
    sentenceIds: [
      "seed-sentence-0001",
      "seed-sentence-0002",
      "seed-sentence-0007",
      "seed-sentence-0003",
      "seed-sentence-0008",
      "seed-sentence-0009",
      "seed-sentence-0010",
      "seed-sentence-0011",
      "seed-sentence-0012",
      "seed-sentence-0013",
    ],
  },
  {
    id: "seed-lesson-software",
    title: "Software Engineering",
    titleTh: "วิศวกรรมซอฟต์แวร์",
    description: "Review, release and debugging language, from a polite request to a trade off.",
    tags: ["software"],
    level: "B1",
    sentenceIds: [
      "seed-sentence-0004",
      "seed-sentence-0005",
      "seed-sentence-0014",
      "seed-sentence-0015",
      "seed-sentence-0016",
      "seed-sentence-0017",
      "seed-sentence-0024",
      "seed-sentence-0025",
      "seed-sentence-0018",
      "seed-sentence-0019",
      "seed-sentence-0020",
      "seed-sentence-0021",
      "seed-sentence-0026",
      "seed-sentence-0022",
      "seed-sentence-0023",
    ],
  },
  {
    id: "seed-lesson-meetings",
    title: "Meetings",
    titleTh: "การประชุม",
    description: "Standup updates, steering a discussion, and disagreeing without bruising anyone.",
    tags: ["meetings"],
    level: "A2",
    sentenceIds: [
      "seed-sentence-0006",
      "seed-sentence-0027",
      "seed-sentence-0030",
      "seed-sentence-0029",
      "seed-sentence-0033",
      "seed-sentence-0034",
      "seed-sentence-0031",
      "seed-sentence-0028",
      "seed-sentence-0032",
      "seed-sentence-0035",
    ],
  },
  {
    id: "seed-lesson-interviews",
    title: "Technical Interviews",
    titleTh: "สัมภาษณ์งานสายเทคนิค",
    description: "Thinking out loud: clarifying, proposing, getting unstuck and asking back.",
    tags: ["interviews"],
    level: "B1",
    sentenceIds: [
      "seed-sentence-0036",
      "seed-sentence-0037",
      "seed-sentence-0041",
      "seed-sentence-0043",
      "seed-sentence-0044",
      "seed-sentence-0038",
      "seed-sentence-0039",
      "seed-sentence-0042",
      "seed-sentence-0045",
      "seed-sentence-0040",
    ],
  },
  {
    id: "seed-lesson-workplace",
    title: "Workplace English",
    titleTh: "ภาษาอังกฤษในที่ทำงาน",
    description: "Leave, email and the small courtesies around the work itself.",
    tags: ["workplace"],
    level: "A2",
    sentenceIds: [
      "seed-sentence-0046",
      "seed-sentence-0049",
      "seed-sentence-0048",
      "seed-sentence-0047",
      "seed-sentence-0050",
    ],
  },
];
