import type { VocabularyEntry } from "@/lib/models";

export type SeedVocab = Omit<VocabularyEntry, "createdAt" | "updatedAt" | "source">;

/**
 * Curated vocabulary for the seed sentences.
 *
 * Everything here is hand-written. The word panel shows only what is present: a missing
 * IPA renders nothing rather than a guess, and a word with no entry gets an explicit
 * "not curated" state. Nothing in the app derives a definition or a pronunciation.
 *
 * `forms` lists the inflections that should resolve to the entry when tapped. They are
 * curated rather than stemmed, because a wrong stem attaches the wrong definition.
 */
export const SEED_VOCABULARY: SeedVocab[] = [
  {
    id: "seed-vocab-where",
    en: "where",
    th: "ที่ไหน",
    pos: "adverb",
    transliteration: "thii nai",
    ipa: "/weə(r)/",
    forms: [],
    contexts: [{ sentenceId: "seed-sentence-0001", meaning: "ถามถึงสถานที่ปลายทาง" }],
    exampleEn: "Where is the meeting room?",
    exampleTh: "ห้องประชุมอยู่ที่ไหน",
    exampleSentenceIds: ["seed-sentence-0001"],
    tags: ["questions"],
    level: "A1",
    saved: false,
  },
  {
    id: "seed-vocab-go",
    en: "go",
    th: "ไป",
    pos: "verb",
    transliteration: "pai",
    ipa: "/ɡəʊ/",
    forms: ["going", "goes", "went", "gone"],
    contexts: [{ sentenceId: "seed-sentence-0001", meaning: "กำลังจะเดินทางไป (รูป going บอกอนาคตอันใกล้)" }],
    exampleEn: "I go to the office on Mondays.",
    exampleTh: "ผมไปออฟฟิศทุกวันจันทร์",
    exampleSentenceIds: ["seed-sentence-0001"],
    tags: ["everyday"],
    level: "A1",
    saved: false,
  },
  {
    id: "seed-vocab-hungry",
    en: "hungry",
    th: "หิว",
    pos: "adjective",
    transliteration: "hiu",
    ipa: "/ˈhʌŋɡri/",
    forms: [],
    contexts: [{ sentenceId: "seed-sentence-0002", meaning: "รู้สึกอยากอาหาร" }],
    exampleEn: "Are you hungry yet?",
    exampleTh: "หิวหรือยัง",
    exampleSentenceIds: ["seed-sentence-0002"],
    tags: ["everyday"],
    level: "A1",
    saved: false,
  },
  {
    id: "seed-vocab-very",
    en: "very",
    th: "มาก",
    pos: "adverb",
    transliteration: "mak",
    ipa: "/ˈveri/",
    forms: [],
    contexts: [{ sentenceId: "seed-sentence-0002", meaning: "ขยายคำคุณศัพท์ให้แรงขึ้น วางไว้หน้าคำที่ขยาย" }],
    exampleEn: "This bug is very hard to reproduce.",
    exampleTh: "บั๊กตัวนี้ทำซ้ำได้ยากมาก",
    exampleSentenceIds: ["seed-sentence-0002"],
    tags: ["everyday"],
    level: "A1",
    saved: false,
  },
  {
    id: "seed-vocab-tomorrow",
    en: "tomorrow",
    th: "พรุ่งนี้",
    pos: "adverb",
    transliteration: "phrung-nii",
    ipa: "/təˈmɒrəʊ/",
    forms: [],
    contexts: [{ sentenceId: "seed-sentence-0003", meaning: "วันถัดจากวันนี้" }],
    exampleEn: "The release is tomorrow.",
    exampleTh: "จะปล่อยตัวนี้พรุ่งนี้",
    exampleSentenceIds: ["seed-sentence-0003"],
    tags: ["time"],
    level: "A1",
    saved: false,
  },
  {
    id: "seed-vocab-call",
    en: "call",
    th: "โทรหา",
    pos: "verb",
    transliteration: "tho ha",
    ipa: "/kɔːl/",
    forms: ["calls", "called", "calling"],
    senseNote: "call (telephone)",
    contexts: [{ sentenceId: "seed-sentence-0003", meaning: "โทรศัพท์หา ไม่ใช่ เรียก" }],
    exampleEn: "Call me when the build finishes.",
    exampleTh: "บิลด์เสร็จแล้วโทรหาผมนะ",
    exampleSentenceIds: ["seed-sentence-0003"],
    tags: ["everyday"],
    level: "A1",
    saved: false,
  },
  {
    id: "seed-vocab-deploy",
    en: "deploy",
    th: "ดีพลอย / นำขึ้นระบบ",
    pos: "verb",
    transliteration: "dii-phloi",
    ipa: "/dɪˈplɔɪ/",
    forms: ["deploys", "deployed", "deploying", "deployment"],
    contexts: [{ sentenceId: "seed-sentence-0004", meaning: "นำโค้ดขึ้นเซิร์ฟเวอร์จริง" }],
    exampleEn: "We deploy every Thursday.",
    exampleTh: "เราดีพลอยทุกวันพฤหัส",
    exampleSentenceIds: ["seed-sentence-0004"],
    tags: ["software"],
    level: "B1",
    saved: false,
  },
  {
    id: "seed-vocab-review",
    en: "review",
    th: "การรีวิว / ตรวจโค้ด",
    pos: "noun",
    transliteration: "kan rii-wiu",
    ipa: "/rɪˈvjuː/",
    forms: ["reviews", "reviewed", "reviewing"],
    senseNote: "review (code review)",
    contexts: [
      { sentenceId: "seed-sentence-0004", meaning: "ขั้นตอนที่เพื่อนร่วมทีมตรวจโค้ดก่อนรวมเข้าระบบ" },
    ],
    exampleEn: "The review is still open.",
    exampleTh: "รีวิวยังไม่ปิด",
    exampleSentenceIds: ["seed-sentence-0004"],
    tags: ["software"],
    level: "B1",
    saved: false,
  },
  {
    id: "seed-vocab-pull-request",
    en: "pull request",
    th: "คำขอรวมโค้ด",
    pos: "noun",
    transliteration: "kham kho ruam khot",
    ipa: "/pʊl rɪˈkwest/",
    forms: ["pull requests", "PR", "PRs"],
    contexts: [{ sentenceId: "seed-sentence-0005", meaning: "คำขอให้รวมโค้ดสาขาของเราเข้ากับสาขาหลัก" }],
    exampleEn: "I opened a pull request this morning.",
    exampleTh: "เช้านี้ผมเปิด pull request ไว้",
    exampleSentenceIds: ["seed-sentence-0005"],
    tags: ["software"],
    level: "B1",
    saved: false,
  },
  {
    id: "seed-vocab-take-a-look",
    en: "look",
    th: "ดู",
    pos: "verb",
    transliteration: "duu",
    ipa: "/lʊk/",
    forms: ["looks", "looked", "looking"],
    senseNote: "take a look at (examine)",
    contexts: [
      {
        sentenceId: "seed-sentence-0005",
        meaning: "ในวลี take another look at = ช่วยดูอีกรอบ สุภาพกว่าการสั่งให้ตรวจ",
      },
    ],
    exampleEn: "Could you look at this error?",
    exampleTh: "ช่วยดูเออเรอร์นี้หน่อยได้ไหม",
    exampleSentenceIds: ["seed-sentence-0005"],
    tags: ["software", "requests"],
    level: "A2",
    saved: false,
  },
  {
    id: "seed-vocab-blocker",
    en: "blocker",
    th: "สิ่งที่ติดขัด",
    pos: "noun",
    transliteration: "sing thii tit khat",
    ipa: "/ˈblɒkə(r)/",
    forms: ["blockers"],
    contexts: [
      { sentenceId: "seed-sentence-0006", meaning: "สิ่งที่ทำให้งานเดินต่อไม่ได้ มักพูดในสแตนด์อัพ" },
    ],
    exampleEn: "My only blocker is the staging database.",
    exampleTh: "สิ่งเดียวที่ติดคือฐานข้อมูล staging",
    exampleSentenceIds: ["seed-sentence-0006"],
    tags: ["meetings"],
    level: "B1",
    saved: false,
  },
  {
    id: "seed-vocab-today",
    en: "today",
    th: "วันนี้",
    pos: "adverb",
    transliteration: "wan nii",
    ipa: "/təˈdeɪ/",
    forms: [],
    contexts: [{ sentenceId: "seed-sentence-0006", meaning: "วันปัจจุบัน วางท้ายประโยคในภาษาอังกฤษ" }],
    exampleEn: "I am working from home today.",
    exampleTh: "วันนี้ผมทำงานที่บ้าน",
    exampleSentenceIds: ["seed-sentence-0006"],
    tags: ["time"],
    level: "A1",
    saved: false,
  },
];
