import type { VocabularyEntryInput } from "@/lib/models";

/**
 * A seed entry. Uses the *input* shape, so a field with a schema default (`forms`,
 * `contexts`, `tags`, `saved`) may simply be left out rather than written as an empty
 * array on ninety entries.
 */
export type SeedVocab = Omit<VocabularyEntryInput, "createdAt" | "updatedAt" | "source">;

/**
 * Curated vocabulary for the seed sentences. Original content, written for this app.
 *
 * Everything here is hand-written. The word panel shows only what is present: a missing
 * IPA renders nothing rather than a guess, and a word with no entry gets an explicit
 * "not curated" state. Nothing in the app derives a definition or a pronunciation.
 *
 * `forms` lists the inflections that should resolve to the entry when tapped. They are
 * curated rather than stemmed, because a wrong stem attaches the wrong definition.
 *
 * Two rules that keep the lookup honest:
 *
 * - **One entry owns a surface form.** `buildVocabLookup` keeps the first entry that
 *   claims a word, so "take" belongs to the task sense and "take off" is reached through
 *   "off". A second claim on the same word would be silently ignored.
 * - **A multi-word headword needs a single-word form**, because the learner taps one
 *   word at a time: "heads up" is found by tapping "heads".
 *
 * `contexts` is what the word means *in that particular sentence*, which is often not
 * the headword sense — "park" in a meeting is not a car park.
 */
export const SEED_VOCABULARY: SeedVocab[] = [
  // ---------------------------------------------------------------- Daily conversation
  {
    id: "seed-vocab-where",
    en: "where",
    th: "ที่ไหน",
    pos: "adverb",
    transliteration: "thii nai",
    ipa: "/weə(r)/",
    contexts: [{ sentenceId: "seed-sentence-0001", meaning: "ถามถึงสถานที่ปลายทาง" }],
    exampleEn: "Where is the meeting room?",
    exampleTh: "ห้องประชุมอยู่ที่ไหน",
    exampleSentenceIds: ["seed-sentence-0001"],
    tags: ["questions"],
    level: "A1",
  },
  {
    id: "seed-vocab-go",
    en: "go",
    th: "ไป",
    pos: "verb",
    transliteration: "pai",
    ipa: "/ɡəʊ/",
    forms: ["going", "goes", "went", "gone"],
    contexts: [{ sentenceId: "seed-sentence-0001", meaning: "กำลังจะเดินทางไป (รูป going บอกอนาคตอันใกล้)" }],
    exampleEn: "I go to the office on Mondays.",
    exampleTh: "ผมไปออฟฟิศทุกวันจันทร์",
    exampleSentenceIds: ["seed-sentence-0001"],
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-hungry",
    en: "hungry",
    th: "หิว",
    pos: "adjective",
    transliteration: "hiu",
    ipa: "/ˈhʌŋɡri/",
    contexts: [{ sentenceId: "seed-sentence-0002", meaning: "รู้สึกอยากอาหาร" }],
    exampleEn: "Are you hungry yet?",
    exampleTh: "หิวหรือยัง",
    exampleSentenceIds: ["seed-sentence-0002"],
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-very",
    en: "very",
    th: "มาก",
    pos: "adverb",
    transliteration: "mak",
    ipa: "/ˈveri/",
    contexts: [{ sentenceId: "seed-sentence-0002", meaning: "ขยายคำคุณศัพท์ให้แรงขึ้น วางไว้หน้าคำที่ขยาย" }],
    exampleEn: "This bug is very hard to reproduce.",
    exampleTh: "บั๊กตัวนี้ทำซ้ำได้ยากมาก",
    exampleSentenceIds: ["seed-sentence-0002"],
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-tomorrow",
    en: "tomorrow",
    th: "พรุ่งนี้",
    pos: "adverb",
    transliteration: "phrung-nii",
    ipa: "/təˈmɒrəʊ/",
    contexts: [
      { sentenceId: "seed-sentence-0003", meaning: "วันถัดจากวันนี้" },
      { sentenceId: "seed-sentence-0049", meaning: "วันถัดจากวันนี้ วางท้ายประโยคในภาษาอังกฤษ" },
    ],
    exampleEn: "The release is tomorrow.",
    exampleTh: "จะปล่อยตัวนี้พรุ่งนี้",
    exampleSentenceIds: ["seed-sentence-0003", "seed-sentence-0049"],
    tags: ["time"],
    level: "A1",
  },
  {
    id: "seed-vocab-call",
    en: "call",
    th: "โทรหา",
    pos: "verb",
    transliteration: "tho ha",
    ipa: "/kɔːl/",
    forms: ["calls", "called", "calling"],
    senseNote: "call (telephone)",
    contexts: [{ sentenceId: "seed-sentence-0003", meaning: "โทรศัพท์หา ไม่ใช่ เรียก" }],
    exampleEn: "Call me when the build finishes.",
    exampleTh: "บิลด์เสร็จแล้วโทรหาผมนะ",
    exampleSentenceIds: ["seed-sentence-0003"],
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-cost",
    en: "cost",
    th: "ราคา / มีราคา",
    pos: "verb",
    transliteration: "ra-kha",
    ipa: "/kɒst/",
    forms: ["costs"],
    contexts: [
      { sentenceId: "seed-sentence-0007", meaning: "เป็นคำกริยา แปลว่า ราคาเท่ากับ ไม่ต้องมี is นำหน้า" },
    ],
    exampleEn: "How much do the tickets cost?",
    exampleTh: "ตั๋วราคาเท่าไหร่",
    exampleSentenceIds: ["seed-sentence-0007"],
    tags: ["everyday", "shopping"],
    level: "A1",
  },
  {
    id: "seed-vocab-how-much",
    en: "how much",
    th: "เท่าไหร่",
    pos: "phrase",
    transliteration: "thao rai",
    ipa: "/haʊ mʌtʃ/",
    forms: ["how"],
    contexts: [{ sentenceId: "seed-sentence-0007", meaning: "ถามจำนวนของสิ่งที่นับไม่ได้ เช่น เงิน" }],
    exampleEn: "How much time do we have left?",
    exampleTh: "เราเหลือเวลาเท่าไหร่",
    exampleSentenceIds: ["seed-sentence-0007"],
    tags: ["questions"],
    level: "A1",
  },
  {
    id: "seed-vocab-again",
    en: "again",
    th: "อีกครั้ง",
    pos: "adverb",
    transliteration: "iik khrang",
    ipa: "/əˈɡen/",
    contexts: [{ sentenceId: "seed-sentence-0008", meaning: "ทำซ้ำอีกหนึ่งรอบ วางท้ายประโยค" }],
    exampleEn: "Could you explain that again?",
    exampleTh: "ช่วยอธิบายอีกครั้งได้ไหม",
    exampleSentenceIds: ["seed-sentence-0008"],
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-please",
    en: "please",
    th: "กรุณา / นะครับ",
    pos: "adverb",
    transliteration: "ka-ru-na",
    ipa: "/pliːz/",
    contexts: [
      {
        sentenceId: "seed-sentence-0008",
        meaning: "ทำให้คำขอสุภาพขึ้น วางท้ายประโยคได้เสมอ ไม่ได้แปลว่า พอใจ",
      },
    ],
    exampleEn: "Please send me the link.",
    exampleTh: "ช่วยส่งลิงก์ให้ผมหน่อยนะครับ",
    exampleSentenceIds: ["seed-sentence-0008"],
    tags: ["everyday", "requests"],
    level: "A1",
  },
  {
    id: "seed-vocab-catch",
    en: "catch",
    th: "ฟังทัน / จับใจความ",
    pos: "verb",
    transliteration: "fang than",
    ipa: "/kætʃ/",
    forms: ["catches", "caught", "catching"],
    senseNote: "catch (hear and understand)",
    contexts: [
      { sentenceId: "seed-sentence-0009", meaning: "ฟังไม่ทัน ไม่ใช่ จับ เป็นวิธีบอกอย่างสุภาพว่าไม่ได้ยิน" },
    ],
    exampleEn: "Sorry, I didn't catch your name.",
    exampleTh: "ขอโทษครับ ผมฟังชื่อคุณไม่ทัน",
    exampleSentenceIds: ["seed-sentence-0009"],
    tags: ["everyday"],
    level: "A2",
  },
  {
    id: "seed-vocab-sorry",
    en: "sorry",
    th: "ขอโทษ",
    pos: "adjective",
    transliteration: "kho thot",
    ipa: "/ˈsɒri/",
    contexts: [
      { sentenceId: "seed-sentence-0009", meaning: "ขอโทษเล็กน้อย ใช้ก่อนขอให้พูดซ้ำ" },
      { sentenceId: "seed-sentence-0030", meaning: "ขอโทษก่อนจะบอกว่าอีกฝ่ายพลาดอะไรไป ทำให้ฟังนุ่มขึ้น" },
      { sentenceId: "seed-sentence-0050", meaning: "ขอโทษที่ตอบช้า ตามด้วย for แล้วคำนาม" },
    ],
    exampleSentenceIds: ["seed-sentence-0009", "seed-sentence-0030", "seed-sentence-0050"],
    exampleEn: "Sorry, I was in a meeting.",
    exampleTh: "ขอโทษครับ ผมติดประชุมอยู่",
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-finish",
    en: "finish",
    th: "เลิก / ทำเสร็จ",
    pos: "verb",
    transliteration: "loek / set",
    ipa: "/ˈfɪnɪʃ/",
    forms: ["finishes", "finished", "finishing"],
    contexts: [
      { sentenceId: "seed-sentence-0010", meaning: "เลิกงาน ไม่ต้องมี to ตามหลัง" },
      { sentenceId: "seed-sentence-0027", meaning: "ทำเสร็จ ใช้รูปอดีต finished คู่กับ yesterday" },
    ],
    exampleEn: "I finished the report last night.",
    exampleTh: "ผมทำรายงานเสร็จเมื่อคืน",
    exampleSentenceIds: ["seed-sentence-0010", "seed-sentence-0027"],
    tags: ["everyday", "work"],
    level: "A2",
  },
  {
    id: "seed-vocab-what-time",
    en: "what time",
    th: "กี่โมง",
    pos: "phrase",
    transliteration: "kii mong",
    ipa: "/wɒt taɪm/",
    forms: ["what"],
    contexts: [{ sentenceId: "seed-sentence-0010", meaning: "ถามเวลานาฬิกา ขึ้นต้นประโยคคำถามเสมอ" }],
    exampleEn: "What time does the demo start?",
    exampleTh: "เดโมเริ่มกี่โมง",
    exampleSentenceIds: ["seed-sentence-0010"],
    tags: ["questions", "time"],
    level: "A1",
  },
  {
    id: "seed-vocab-meet",
    en: "meet",
    th: "เจอ / พบ",
    pos: "verb",
    transliteration: "joe",
    ipa: "/miːt/",
    forms: ["meets", "met"],
    senseNote: "meet (see someone at an arranged place)",
    contexts: [{ sentenceId: "seed-sentence-0011", meaning: "นัดเจอกัน ไม่ต้องมี each other ก็ได้" }],
    exampleEn: "Let's meet after lunch.",
    exampleTh: "เจอกันหลังมื้อเที่ยงนะ",
    exampleSentenceIds: ["seed-sentence-0011"],
    tags: ["everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-in-front-of",
    en: "in front of",
    th: "ข้างหน้า / ตรงหน้า",
    pos: "preposition",
    transliteration: "khang na",
    ipa: "/ɪn frʌnt ɒv/",
    forms: ["front"],
    contexts: [
      { sentenceId: "seed-sentence-0011", meaning: "อยู่ด้านหน้าของสถานที่ ต้องมี of เสมอเมื่อตามด้วยคำนาม" },
    ],
    exampleEn: "I'll wait in front of the lobby.",
    exampleTh: "ผมจะรออยู่หน้าล็อบบี้",
    exampleSentenceIds: ["seed-sentence-0011"],
    tags: ["everyday", "directions"],
    level: "A2",
  },
  {
    id: "seed-vocab-rain",
    en: "rain",
    th: "ฝนตก",
    pos: "verb",
    transliteration: "fon tok",
    ipa: "/reɪn/",
    forms: ["rains", "rained", "raining"],
    contexts: [
      {
        sentenceId: "seed-sentence-0012",
        meaning: "ภาษาอังกฤษต้องมีประธาน it นำหน้าเสมอ แม้ไม่มีผู้กระทำจริง",
      },
    ],
    exampleEn: "It rained all weekend.",
    exampleTh: "ฝนตกทั้งสุดสัปดาห์",
    exampleSentenceIds: ["seed-sentence-0012"],
    tags: ["everyday", "weather"],
    level: "A2",
  },
  {
    id: "seed-vocab-all",
    en: "all",
    th: "ตลอด / ทั้ง",
    pos: "adverb",
    transliteration: "ta-lot",
    ipa: "/ɔːl/",
    senseNote: "all (for the whole of a period)",
    contexts: [{ sentenceId: "seed-sentence-0012", meaning: "ตลอดช่วงเวลานั้น เช่น all morning ทั้งเช้า" }],
    exampleEn: "The build was broken all day.",
    exampleTh: "บิลด์พังตลอดทั้งวัน",
    exampleSentenceIds: ["seed-sentence-0012"],
    tags: ["time"],
    level: "A2",
  },
  {
    id: "seed-vocab-make-it",
    en: "make it",
    th: "มาได้ / ไปได้",
    pos: "phrase",
    transliteration: "ma dai",
    ipa: "/meɪk ɪt/",
    forms: ["make", "makes", "made", "making"],
    senseNote: "make it (manage to attend)",
    contexts: [{ sentenceId: "seed-sentence-0013", meaning: "ไปร่วมงานได้ ไม่ได้แปลว่า ทำมัน" }],
    exampleEn: "Can you make it to the standup?",
    exampleTh: "คุณเข้าสแตนด์อัพได้ไหม",
    exampleSentenceIds: ["seed-sentence-0013"],
    tags: ["everyday", "invitations"],
    level: "B1",
  },
  {
    id: "seed-vocab-tonight",
    en: "tonight",
    th: "คืนนี้",
    pos: "adverb",
    transliteration: "khuen nii",
    ipa: "/təˈnaɪt/",
    contexts: [{ sentenceId: "seed-sentence-0013", meaning: "ค่ำของวันนี้ วางท้ายประโยค" }],
    exampleEn: "The deploy window is tonight.",
    exampleTh: "ช่วงเวลาดีพลอยคือคืนนี้",
    exampleSentenceIds: ["seed-sentence-0013"],
    tags: ["time"],
    level: "A1",
  },

  // ------------------------------------------------------------- Software engineering
  {
    id: "seed-vocab-deploy",
    en: "deploy",
    th: "ดีพลอย / นำขึ้นระบบ",
    pos: "verb",
    transliteration: "dii-phloi",
    ipa: "/dɪˈplɔɪ/",
    forms: ["deploys", "deployed", "deploying", "deployment"],
    contexts: [{ sentenceId: "seed-sentence-0004", meaning: "นำโค้ดขึ้นเซิร์ฟเวอร์จริง" }],
    exampleEn: "We deploy every Thursday.",
    exampleTh: "เราดีพลอยทุกวันพฤหัส",
    exampleSentenceIds: ["seed-sentence-0004"],
    tags: ["software"],
    level: "B1",
  },
  {
    id: "seed-vocab-review",
    en: "review",
    th: "การรีวิว / ตรวจโค้ด",
    pos: "noun",
    transliteration: "kan rii-wiu",
    ipa: "/rɪˈvjuː/",
    forms: ["reviews", "reviewed", "reviewing"],
    senseNote: "review (code review)",
    contexts: [
      { sentenceId: "seed-sentence-0004", meaning: "ขั้นตอนที่เพื่อนร่วมทีมตรวจโค้ดก่อนรวมเข้าระบบ" },
    ],
    exampleEn: "The review is still open.",
    exampleTh: "รีวิวยังไม่ปิด",
    exampleSentenceIds: ["seed-sentence-0004"],
    tags: ["software"],
    level: "B1",
  },
  {
    id: "seed-vocab-pull-request",
    en: "pull request",
    th: "คำขอรวมโค้ด",
    pos: "noun",
    transliteration: "kham kho ruam khot",
    ipa: "/pʊl rɪˈkwest/",
    forms: ["pull", "PR", "PRs"],
    contexts: [
      { sentenceId: "seed-sentence-0005", meaning: "คำขอให้รวมโค้ดสาขาของเราเข้ากับสาขาหลัก" },
      { sentenceId: "seed-sentence-0015", meaning: "ที่เดียวกับที่ผู้รีวิวฝากความเห็นไว้" },
    ],
    exampleEn: "I opened a pull request this morning.",
    exampleTh: "เช้านี้ผมเปิด pull request ไว้",
    exampleSentenceIds: ["seed-sentence-0005", "seed-sentence-0015"],
    tags: ["software"],
    level: "B1",
  },
  {
    id: "seed-vocab-take-a-look",
    en: "look",
    th: "ดู",
    pos: "verb",
    transliteration: "duu",
    ipa: "/lʊk/",
    forms: ["looks", "looked", "looking"],
    senseNote: "take a look at (examine)",
    contexts: [
      {
        sentenceId: "seed-sentence-0005",
        meaning: "ในวลี take another look at = ช่วยดูอีกรอบ สุภาพกว่าการสั่งให้ตรวจ",
      },
      { sentenceId: "seed-sentence-0045", meaning: "ในวลี what does it look like = เป็นอย่างไร" },
    ],
    exampleEn: "Could you look at this error?",
    exampleTh: "ช่วยดูเออเรอร์นี้หน่อยได้ไหม",
    exampleSentenceIds: ["seed-sentence-0005", "seed-sentence-0045"],
    tags: ["software", "requests"],
    level: "A2",
  },
  {
    id: "seed-vocab-build",
    en: "build",
    th: "บิลด์ / การคอมไพล์",
    pos: "noun",
    transliteration: "bin",
    ipa: "/bɪld/",
    forms: ["builds", "built", "building"],
    senseNote: "build (the compiled output of a CI run)",
    contexts: [{ sentenceId: "seed-sentence-0014", meaning: "รอบการคอมไพล์และทดสอบอัตโนมัติ เป็นคำนาม" }],
    exampleEn: "The build takes about six minutes.",
    exampleTh: "บิลด์ใช้เวลาประมาณหกนาที",
    exampleSentenceIds: ["seed-sentence-0014"],
    tags: ["software"],
    level: "B1",
  },
  {
    id: "seed-vocab-branch",
    en: "branch",
    th: "สาขาโค้ด / แบรนช์",
    pos: "noun",
    transliteration: "sa-kha khot",
    ipa: "/brɑːntʃ/",
    forms: ["branches", "branched", "branching"],
    contexts: [{ sentenceId: "seed-sentence-0014", meaning: "เส้นทางโค้ดแยก main คือสาขาหลักของโปรเจกต์" }],
    exampleEn: "Push your branch and I'll look at it.",
    exampleTh: "พุชแบรนช์ขึ้นมา เดี๋ยวผมดูให้",
    exampleSentenceIds: ["seed-sentence-0014"],
    tags: ["software"],
    level: "B1",
  },
  {
    id: "seed-vocab-comment",
    en: "comment",
    th: "คอมเมนต์ / ความเห็น",
    pos: "noun",
    transliteration: "khwam hen",
    ipa: "/ˈkɒment/",
    forms: ["comments", "commented", "commenting"],
    contexts: [
      { sentenceId: "seed-sentence-0015", meaning: "ข้อสังเกตที่ผู้รีวิวฝากไว้ในโค้ด ใช้คู่กับ leave" },
    ],
    exampleEn: "I replied to your comment.",
    exampleTh: "ผมตอบคอมเมนต์ของคุณแล้ว",
    exampleSentenceIds: ["seed-sentence-0015"],
    tags: ["software", "review"],
    level: "B1",
  },
  {
    id: "seed-vocab-a-few",
    en: "a few",
    th: "สองสาม",
    pos: "phrase",
    transliteration: "song sam",
    ipa: "/ə fjuː/",
    forms: ["few"],
    contexts: [
      { sentenceId: "seed-sentence-0015", meaning: "จำนวนน้อยแต่ไม่ใช่ศูนย์ ใช้กับคำนามนับได้เท่านั้น" },
    ],
    exampleEn: "I have a few questions about the design.",
    exampleTh: "ผมมีคำถามเรื่องดีไซน์อยู่สองสามข้อ",
    exampleSentenceIds: ["seed-sentence-0015"],
    tags: ["software"],
    level: "A2",
  },
  {
    id: "seed-vocab-function",
    en: "function",
    th: "ฟังก์ชัน",
    pos: "noun",
    transliteration: "fang-chan",
    ipa: "/ˈfʌŋkʃn/",
    forms: ["functions"],
    contexts: [{ sentenceId: "seed-sentence-0016", meaning: "หน่วยย่อยของโค้ดที่ทำงานอย่างหนึ่ง" }],
    exampleEn: "Split this function into two.",
    exampleTh: "แยกฟังก์ชันนี้ออกเป็นสองอัน",
    exampleSentenceIds: ["seed-sentence-0016"],
    tags: ["software"],
    level: "A2",
  },
  {
    id: "seed-vocab-at-once",
    en: "at once",
    th: "พร้อมกันในคราวเดียว",
    pos: "phrase",
    transliteration: "phrom kan",
    ipa: "/ət wʌns/",
    forms: ["once"],
    contexts: [{ sentenceId: "seed-sentence-0016", meaning: "ในเวลาเดียวกัน ตรงนี้ไม่ได้แปลว่า ทันที" }],
    exampleEn: "Don't change three things at once.",
    exampleTh: "อย่าแก้สามอย่างพร้อมกัน",
    exampleSentenceIds: ["seed-sentence-0016"],
    tags: ["software"],
    level: "B1",
  },
  {
    id: "seed-vocab-reproduce",
    en: "reproduce",
    th: "ทำซ้ำให้เกิดอีก",
    pos: "verb",
    transliteration: "tham sam",
    ipa: "/ˌriːprəˈdjuːs/",
    forms: ["reproduces", "reproduced", "reproducing"],
    contexts: [{ sentenceId: "seed-sentence-0017", meaning: "ทำให้บั๊กเกิดขึ้นอีกครั้งเพื่อหาสาเหตุ" }],
    exampleEn: "I can't reproduce it on staging.",
    exampleTh: "ผมทำให้เกิดซ้ำบน staging ไม่ได้",
    exampleSentenceIds: ["seed-sentence-0017"],
    tags: ["software", "debugging"],
    level: "B1",
  },
  {
    id: "seed-vocab-machine",
    en: "machine",
    th: "เครื่อง",
    pos: "noun",
    transliteration: "khrueang",
    ipa: "/məˈʃiːn/",
    forms: ["machines"],
    senseNote: "machine (a developer's own computer)",
    contexts: [{ sentenceId: "seed-sentence-0017", meaning: "คอมพิวเตอร์ของคนคนนั้น ไม่ใช่ เครื่องจักร" }],
    exampleEn: "It only fails on my machine.",
    exampleTh: "มันพังเฉพาะบนเครื่องผม",
    exampleSentenceIds: ["seed-sentence-0017"],
    tags: ["software"],
    level: "A2",
  },
  {
    id: "seed-vocab-edge-case",
    en: "edge case",
    th: "กรณีสุดขอบ",
    pos: "noun",
    transliteration: "ko-ra-nii sut khop",
    ipa: "/edʒ keɪs/",
    forms: ["edge", "case", "cases"],
    contexts: [
      { sentenceId: "seed-sentence-0018", meaning: "กรณีที่เกิดยากแต่ทำให้โปรแกรมพัง เช่น ข้อมูลว่าง" },
    ],
    exampleEn: "Empty input is the edge case we missed.",
    exampleTh: "อินพุตว่างคือกรณีสุดขอบที่เรามองข้าม",
    exampleSentenceIds: ["seed-sentence-0018"],
    tags: ["software", "testing"],
    level: "B2",
  },
  {
    id: "seed-vocab-cover",
    en: "cover",
    th: "ครอบคลุม",
    pos: "verb",
    transliteration: "khrop khlum",
    ipa: "/ˈkʌvə(r)/",
    forms: ["covers", "covered", "covering", "coverage"],
    senseNote: "cover (of a test: exercise a case)",
    contexts: [{ sentenceId: "seed-sentence-0018", meaning: "เทสต์ตรวจถึงกรณีนั้นแล้ว ไม่ใช่ ปกปิด" }],
    exampleEn: "These tests cover the happy path only.",
    exampleTh: "เทสต์ชุดนี้ครอบคลุมแค่เส้นทางปกติ",
    exampleSentenceIds: ["seed-sentence-0018"],
    tags: ["software", "testing"],
    level: "B2",
  },
  {
    id: "seed-vocab-roll-back",
    en: "roll back",
    th: "ย้อนกลับเวอร์ชัน",
    pos: "verb",
    transliteration: "yon klap",
    ipa: "/rəʊl bæk/",
    forms: ["roll", "rolled", "rolling", "rollback"],
    contexts: [{ sentenceId: "seed-sentence-0019", meaning: "ถอนรีลีสกลับไปเวอร์ชันก่อนหน้าเพราะมีปัญหา" }],
    exampleEn: "We rolled back within ten minutes.",
    exampleTh: "เราย้อนกลับภายในสิบนาที",
    exampleSentenceIds: ["seed-sentence-0019"],
    tags: ["software", "release"],
    level: "B2",
  },
  {
    id: "seed-vocab-spike",
    en: "spike",
    th: "พุ่งขึ้นอย่างรวดเร็ว",
    pos: "verb",
    transliteration: "phung khuen",
    ipa: "/spaɪk/",
    forms: ["spikes", "spiked", "spiking"],
    senseNote: "spike (rise sharply for a short time)",
    contexts: [
      { sentenceId: "seed-sentence-0019", meaning: "ค่าพุ่งสูงขึ้นทันที ใช้กับกราฟมอนิเตอร์บ่อยมาก" },
    ],
    exampleEn: "Error rates spiked after the release.",
    exampleTh: "อัตราเออเรอร์พุ่งขึ้นหลังปล่อยรีลีส",
    exampleSentenceIds: ["seed-sentence-0019"],
    tags: ["software", "monitoring"],
    level: "B2",
  },
  {
    id: "seed-vocab-migration",
    en: "migration",
    th: "การย้ายโครงสร้างข้อมูล",
    pos: "noun",
    transliteration: "kan yai khrong sang",
    ipa: "/maɪˈɡreɪʃn/",
    forms: ["migrations", "migrate", "migrated"],
    contexts: [
      {
        sentenceId: "seed-sentence-0020",
        meaning: "สคริปต์ที่เปลี่ยนโครงสร้างฐานข้อมูลจากเวอร์ชันหนึ่งไปอีกเวอร์ชัน",
      },
    ],
    exampleEn: "Run the migration before the deploy.",
    exampleTh: "รัน migration ก่อนดีพลอย",
    exampleSentenceIds: ["seed-sentence-0020"],
    tags: ["software", "data"],
    level: "B2",
  },
  {
    id: "seed-vocab-backwards-compatible",
    en: "backwards compatible",
    th: "เข้ากันได้กับของเดิม",
    pos: "adjective",
    transliteration: "khao kan dai kap khong doem",
    ipa: "/ˈbækwədz kəmˈpætəbl/",
    forms: ["backwards", "backward", "compatible"],
    contexts: [
      { sentenceId: "seed-sentence-0020", meaning: "ของใหม่ยังทำงานกับเวอร์ชันเก่าได้ ไม่ทำให้ของเดิมพัง" },
    ],
    exampleEn: "Keep the old column so the change stays backwards compatible.",
    exampleTh: "เก็บคอลัมน์เดิมไว้ การแก้จะได้เข้ากันได้กับของเดิม",
    exampleSentenceIds: ["seed-sentence-0020"],
    tags: ["software"],
    level: "C1",
  },
  {
    id: "seed-vocab-walk-through",
    en: "walk through",
    th: "พาไล่ดูทีละขั้น",
    pos: "verb",
    transliteration: "pha lai duu",
    ipa: "/wɔːk θruː/",
    forms: ["walk", "walks", "walked", "walking"],
    contexts: [
      { sentenceId: "seed-sentence-0021", meaning: "อธิบายทีละส่วนให้ฟัง ไม่ได้แปลว่า เดินผ่าน" },
      { sentenceId: "seed-sentence-0041", meaning: "ไล่ตัวอย่างทีละขั้นให้ผู้สัมภาษณ์เห็นวิธีคิด" },
    ],
    exampleEn: "Let me walk you through the log.",
    exampleTh: "เดี๋ยวผมพาไล่ดูล็อกทีละบรรทัด",
    exampleSentenceIds: ["seed-sentence-0021", "seed-sentence-0041"],
    tags: ["software", "explaining"],
    level: "B2",
  },
  {
    id: "seed-vocab-architecture",
    en: "architecture",
    th: "สถาปัตยกรรมระบบ",
    pos: "noun",
    transliteration: "sa-tha-pat-ta-ya-kam",
    ipa: "/ˈɑːkɪtektʃə(r)/",
    contexts: [
      { sentenceId: "seed-sentence-0021", meaning: "ภาพรวมว่าระบบประกอบด้วยส่วนใดและคุยกันอย่างไร" },
    ],
    exampleEn: "The architecture has three services.",
    exampleTh: "สถาปัตยกรรมนี้มีสามเซอร์วิส",
    exampleSentenceIds: ["seed-sentence-0021"],
    tags: ["software"],
    level: "B2",
  },
  {
    id: "seed-vocab-trade",
    en: "trade",
    th: "แลก",
    pos: "verb",
    transliteration: "laek",
    ipa: "/treɪd/",
    forms: ["trades", "traded", "trading"],
    senseNote: "trade X for Y (accept less of one thing to get more of another)",
    contexts: [
      { sentenceId: "seed-sentence-0022", meaning: "ยอมเสียอย่างหนึ่งเพื่อได้อีกอย่าง ตามด้วย for เสมอ" },
      { sentenceId: "seed-sentence-0040", meaning: "ยอมใช้หน่วยความจำมากขึ้นเพื่อให้เร็วขึ้น" },
    ],
    exampleEn: "We traded simplicity for speed.",
    exampleTh: "เราแลกความเรียบง่ายกับความเร็ว",
    exampleSentenceIds: ["seed-sentence-0022", "seed-sentence-0040"],
    tags: ["software", "design"],
    level: "C1",
  },
  {
    id: "seed-vocab-readability",
    en: "readability",
    th: "ความอ่านง่ายของโค้ด",
    pos: "noun",
    transliteration: "khwam an ngai",
    ipa: "/ˌriːdəˈbɪləti/",
    forms: ["readable"],
    contexts: [{ sentenceId: "seed-sentence-0022", meaning: "ความง่ายที่คนอื่นจะอ่านโค้ดนี้เข้าใจ" }],
    exampleEn: "Readability matters more than cleverness.",
    exampleTh: "ความอ่านง่ายสำคัญกว่าความฉลาดของโค้ด",
    exampleSentenceIds: ["seed-sentence-0022"],
    tags: ["software"],
    level: "C1",
  },
  {
    id: "seed-vocab-root-cause",
    en: "root cause",
    th: "สาเหตุที่แท้จริง",
    pos: "noun",
    transliteration: "sa-het thii thae ching",
    ipa: "/ruːt kɔːz/",
    forms: ["root", "cause", "causes"],
    contexts: [{ sentenceId: "seed-sentence-0023", meaning: "ต้นตอจริง ไม่ใช่อาการที่มองเห็น" }],
    exampleEn: "We still haven't found the root cause.",
    exampleTh: "เรายังหาสาเหตุที่แท้จริงไม่เจอ",
    exampleSentenceIds: ["seed-sentence-0023"],
    tags: ["software", "debugging"],
    level: "B2",
  },
  {
    id: "seed-vocab-race-condition",
    en: "race condition",
    th: "ภาวะแย่งกันทำงาน",
    pos: "noun",
    transliteration: "pha-wa yaeng kan",
    ipa: "/reɪs kənˈdɪʃn/",
    forms: ["race"],
    contexts: [
      { sentenceId: "seed-sentence-0023", meaning: "บั๊กที่เกิดเมื่อสองงานทำพร้อมกันแล้วลำดับไม่แน่นอน" },
    ],
    exampleEn: "That only happens under a race condition.",
    exampleTh: "อาการนั้นเกิดเฉพาะตอนมีภาวะแย่งกันทำงาน",
    exampleSentenceIds: ["seed-sentence-0023"],
    tags: ["software", "concurrency"],
    level: "C1",
  },
  {
    id: "seed-vocab-rebase",
    en: "rebase",
    th: "รีเบส / ย้ายฐานคอมมิต",
    pos: "verb",
    transliteration: "rii-bet",
    ipa: "/ˌriːˈbeɪs/",
    forms: ["rebases", "rebased", "rebasing"],
    contexts: [
      { sentenceId: "seed-sentence-0024", meaning: "ย้ายคอมมิตของเราไปต่อท้ายสาขาหลักที่อัปเดตแล้ว" },
    ],
    exampleEn: "Rebase first, then force push.",
    exampleTh: "รีเบสก่อน แล้วค่อยฟอร์ซพุช",
    exampleSentenceIds: ["seed-sentence-0024"],
    tags: ["software", "git"],
    level: "B2",
  },
  {
    id: "seed-vocab-merge",
    en: "merge",
    th: "เมิร์จ / รวมโค้ด",
    pos: "verb",
    transliteration: "moet",
    ipa: "/mɜːdʒ/",
    forms: ["merges", "merged", "merging"],
    contexts: [{ sentenceId: "seed-sentence-0024", meaning: "รวมสาขาของเราเข้ากับสาขาหลัก" }],
    exampleEn: "I'll merge it once the tests pass.",
    exampleTh: "เทสต์ผ่านแล้วผมจะเมิร์จให้",
    exampleSentenceIds: ["seed-sentence-0024"],
    tags: ["software", "git"],
    level: "B1",
  },
  {
    id: "seed-vocab-change",
    en: "change",
    th: "การแก้ไข",
    pos: "noun",
    transliteration: "kan kae khai",
    ipa: "/tʃeɪndʒ/",
    forms: ["changes", "changed", "changing"],
    senseNote: "change (one set of edits submitted together)",
    contexts: [
      { sentenceId: "seed-sentence-0025", meaning: "ชุดการแก้ที่ส่งไปรีวิวรอบเดียว เป็นคำนามนับได้" },
    ],
    exampleEn: "This change touches four files.",
    exampleTh: "การแก้ครั้งนี้แตะสี่ไฟล์",
    exampleSentenceIds: ["seed-sentence-0025"],
    tags: ["software", "review"],
    level: "B1",
  },
  {
    id: "seed-vocab-need",
    en: "need",
    th: "จำเป็น / ต้อง",
    pos: "verb",
    transliteration: "cham-pen",
    ipa: "/niːd/",
    forms: ["needs", "needed", "needing"],
    contexts: [
      {
        sentenceId: "seed-sentence-0025",
        meaning: "ในวลี than it needs to be = เกินความจำเป็น เป็นคำติที่สุภาพ",
      },
    ],
    exampleEn: "This takes longer than it needs to.",
    exampleTh: "อันนี้ใช้เวลานานเกินความจำเป็น",
    exampleSentenceIds: ["seed-sentence-0025"],
    tags: ["software", "review"],
    level: "B2",
  },
  {
    id: "seed-vocab-ship",
    en: "ship",
    th: "ปล่อยขึ้นใช้งานจริง",
    pos: "verb",
    transliteration: "ploi khuen",
    ipa: "/ʃɪp/",
    forms: ["ships", "shipped", "shipping"],
    senseNote: "ship (release software to users)",
    contexts: [{ sentenceId: "seed-sentence-0026", meaning: "ปล่อยของให้ผู้ใช้ได้ใช้ ไม่ได้แปลว่า เรือ" }],
    exampleEn: "We shipped it on Friday.",
    exampleTh: "เราปล่อยขึ้นใช้งานจริงเมื่อวันศุกร์",
    exampleSentenceIds: ["seed-sentence-0026"],
    tags: ["software", "release"],
    level: "B2",
  },
  {
    id: "seed-vocab-feature-flag",
    en: "feature flag",
    th: "สวิตช์เปิดปิดฟีเจอร์",
    pos: "noun",
    transliteration: "sa-wit poet pit",
    ipa: "/ˈfiːtʃə(r) flæɡ/",
    forms: ["feature", "flag", "flags"],
    contexts: [
      { sentenceId: "seed-sentence-0026", meaning: "สวิตช์ที่ทำให้ปล่อยโค้ดได้โดยยังไม่เปิดให้ผู้ใช้เห็น" },
    ],
    exampleEn: "It's already live behind a feature flag.",
    exampleTh: "มันขึ้นระบบแล้ว แต่ยังซ่อนอยู่หลังสวิตช์ฟีเจอร์",
    exampleSentenceIds: ["seed-sentence-0026"],
    tags: ["software", "release"],
    level: "C1",
  },

  // ------------------------------------------------------------------------- Meetings
  {
    id: "seed-vocab-blocker",
    en: "blocker",
    th: "สิ่งที่ติดขัด",
    pos: "noun",
    transliteration: "sing thii tit khat",
    ipa: "/ˈblɒkə(r)/",
    forms: ["blockers"],
    contexts: [
      { sentenceId: "seed-sentence-0006", meaning: "สิ่งที่ทำให้งานเดินต่อไม่ได้ มักพูดในสแตนด์อัพ" },
    ],
    exampleEn: "My only blocker is the staging database.",
    exampleTh: "สิ่งเดียวที่ติดคือฐานข้อมูล staging",
    exampleSentenceIds: ["seed-sentence-0006"],
    tags: ["meetings"],
    level: "B1",
  },
  {
    id: "seed-vocab-today",
    en: "today",
    th: "วันนี้",
    pos: "adverb",
    transliteration: "wan nii",
    ipa: "/təˈdeɪ/",
    contexts: [{ sentenceId: "seed-sentence-0006", meaning: "วันปัจจุบัน วางท้ายประโยคในภาษาอังกฤษ" }],
    exampleEn: "I am working from home today.",
    exampleTh: "วันนี้ผมทำงานที่บ้าน",
    exampleSentenceIds: ["seed-sentence-0006"],
    tags: ["time"],
    level: "A1",
  },
  {
    id: "seed-vocab-yesterday",
    en: "yesterday",
    th: "เมื่อวาน",
    pos: "adverb",
    transliteration: "muea wan",
    ipa: "/ˈjestədeɪ/",
    contexts: [
      { sentenceId: "seed-sentence-0027", meaning: "วันก่อนหน้าวันนี้ บังคับให้กริยาต้องเป็นรูปอดีต" },
    ],
    exampleEn: "Yesterday I reviewed two pull requests.",
    exampleTh: "เมื่อวานผมรีวิวไปสองอัน",
    exampleSentenceIds: ["seed-sentence-0027"],
    tags: ["time", "meetings"],
    level: "A1",
  },
  {
    id: "seed-vocab-park",
    en: "park",
    th: "พักเรื่องไว้ก่อน",
    pos: "verb",
    transliteration: "phak wai kon",
    ipa: "/pɑːk/",
    forms: ["parks", "parked", "parking"],
    senseNote: "park (set a topic aside for later)",
    contexts: [
      { sentenceId: "seed-sentence-0028", meaning: "พักหัวข้อไว้ก่อนเพื่อไม่ให้ประชุมยืดเยื้อ ไม่ใช่ จอดรถ" },
    ],
    exampleEn: "Let's park the naming discussion.",
    exampleTh: "เรื่องตั้งชื่อขอพักไว้ก่อนนะ",
    exampleSentenceIds: ["seed-sentence-0028"],
    tags: ["meetings"],
    level: "B2",
  },
  {
    id: "seed-vocab-come-back-to",
    en: "come back to",
    th: "กลับมาคุยต่อ",
    pos: "phrase",
    transliteration: "klap ma khui to",
    ipa: "/kʌm bæk tuː/",
    forms: ["come", "comes", "came", "back"],
    contexts: [
      {
        sentenceId: "seed-sentence-0028",
        meaning: "กลับมาที่หัวข้อเดิมภายหลัง ต้องมี to ก่อนสิ่งที่จะกลับมาคุย",
      },
    ],
    exampleEn: "We'll come back to this next week.",
    exampleTh: "เราจะกลับมาคุยเรื่องนี้อาทิตย์หน้า",
    exampleSentenceIds: ["seed-sentence-0028"],
    tags: ["meetings"],
    level: "B1",
  },
  {
    id: "seed-vocab-agenda",
    en: "agenda",
    th: "วาระการประชุม",
    pos: "noun",
    transliteration: "wa-ra kan pra-chum",
    ipa: "/əˈdʒendə/",
    forms: ["agendas"],
    contexts: [{ sentenceId: "seed-sentence-0029", meaning: "รายการหัวข้อที่จะคุยกันในการประชุม" }],
    exampleEn: "The agenda is in the invite.",
    exampleTh: "วาระอยู่ในคำเชิญประชุม",
    exampleSentenceIds: ["seed-sentence-0029"],
    tags: ["meetings"],
    level: "B1",
  },
  {
    id: "seed-vocab-add",
    en: "add",
    th: "เพิ่ม",
    pos: "verb",
    transliteration: "phoem",
    ipa: "/æd/",
    forms: ["adds", "added", "adding"],
    contexts: [
      { sentenceId: "seed-sentence-0029", meaning: "เพิ่มเข้าไปในรายการ ใช้ add A to B" },
      { sentenceId: "seed-sentence-0018", meaning: "เขียนเทสต์เพิ่มเข้าไปในชุดที่มีอยู่" },
    ],
    exampleEn: "Add me to that thread, please.",
    exampleTh: "ช่วยเพิ่มผมเข้าไปในเธรดนั้นด้วยครับ",
    exampleSentenceIds: ["seed-sentence-0029", "seed-sentence-0018"],
    tags: ["meetings"],
    level: "A1",
  },
  {
    id: "seed-vocab-mute",
    en: "mute",
    th: "ปิดไมค์",
    pos: "noun",
    transliteration: "pit mai",
    ipa: "/mjuːt/",
    forms: ["muted", "muting", "mutes"],
    senseNote: "on mute (with the microphone switched off)",
    contexts: [
      { sentenceId: "seed-sentence-0030", meaning: "ในวลี on mute = ไมค์ปิดอยู่ พูดแล้วไม่มีใครได้ยิน" },
    ],
    exampleEn: "You've been on mute this whole time.",
    exampleTh: "คุณปิดไมค์มาตลอดเลย",
    exampleSentenceIds: ["seed-sentence-0030"],
    tags: ["meetings", "remote"],
    level: "A2",
  },
  {
    id: "seed-vocab-summarise",
    en: "summarise",
    th: "สรุป",
    pos: "verb",
    transliteration: "sa-rup",
    ipa: "/ˈsʌməraɪz/",
    forms: ["summarize", "summarises", "summarizes", "summarised", "summarized", "summary"],
    contexts: [
      {
        sentenceId: "seed-sentence-0031",
        meaning: "ในวลี to summarise = สรุปคือ ใช้เปิดประโยคก่อนปิดประชุม",
      },
    ],
    exampleEn: "Let me summarise what we decided.",
    exampleTh: "ขอสรุปสิ่งที่เราตัดสินใจกันนะครับ",
    exampleSentenceIds: ["seed-sentence-0031"],
    tags: ["meetings"],
    level: "B1",
  },
  {
    id: "seed-vocab-agree",
    en: "agree",
    th: "ตกลง / เห็นพ้อง",
    pos: "verb",
    transliteration: "tok long",
    ipa: "/əˈɡriː/",
    forms: ["agrees", "agreed", "agreeing", "agreement"],
    contexts: [{ sentenceId: "seed-sentence-0031", meaning: "ตกลงกันได้ ใช้ agree on + สิ่งที่ตกลง" }],
    exampleEn: "We agreed on the deadline.",
    exampleTh: "เราตกลงกันเรื่องกำหนดส่งแล้ว",
    exampleSentenceIds: ["seed-sentence-0031"],
    tags: ["meetings"],
    level: "A2",
  },
  {
    id: "seed-vocab-differently",
    en: "differently",
    th: "ต่างออกไป",
    pos: "adverb",
    transliteration: "tang ok pai",
    ipa: "/ˈdɪfrəntli/",
    forms: ["different"],
    contexts: [
      {
        sentenceId: "seed-sentence-0032",
        meaning: "ในวลี I see it differently = ผมมองต่าง เป็นการค้านอย่างสุภาพ",
      },
    ],
    exampleEn: "Our team does it differently.",
    exampleTh: "ทีมเราทำอีกแบบหนึ่ง",
    exampleSentenceIds: ["seed-sentence-0032"],
    tags: ["meetings", "disagreeing"],
    level: "B2",
  },
  {
    id: "seed-vocab-see",
    en: "see",
    th: "มอง / เห็นว่า",
    pos: "verb",
    transliteration: "mong",
    ipa: "/siː/",
    forms: ["sees", "saw", "seen", "seeing"],
    senseNote: "see it differently (hold a different view)",
    contexts: [{ sentenceId: "seed-sentence-0032", meaning: "มองเรื่องนั้นอีกแบบ ไม่ได้แปลว่า เห็นด้วยตา" }],
    exampleEn: "I see your point, but the cost worries me.",
    exampleTh: "ผมเข้าใจประเด็นคุณ แต่ยังกังวลเรื่องต้นทุน",
    exampleSentenceIds: ["seed-sentence-0032"],
    tags: ["meetings", "disagreeing"],
    level: "B1",
  },
  {
    id: "seed-vocab-one",
    en: "one",
    th: "อัน / เรื่อง",
    pos: "pronoun",
    transliteration: "an",
    ipa: "/wʌn/",
    forms: ["ones"],
    senseNote: "this one (standing in for a noun already mentioned)",
    contexts: [
      {
        sentenceId: "seed-sentence-0034",
        meaning: "แทนสิ่งที่พูดถึงไปแล้ว เช่น งานชิ้นนี้ ทำให้ไม่ต้องพูดคำนามซ้ำ",
      },
    ],
    exampleEn: "I'll take this one, you take the next.",
    exampleTh: "อันนี้ผมเอา อันต่อไปคุณรับไป",
    exampleSentenceIds: ["seed-sentence-0034"],
    tags: ["meetings", "everyday"],
    level: "A2",
  },
  {
    id: "seed-vocab-push",
    en: "push",
    th: "เลื่อนออกไป",
    pos: "verb",
    transliteration: "luean ok pai",
    ipa: "/pʊʃ/",
    forms: ["pushes", "pushed", "pushing"],
    senseNote: "push (move an event to a later time)",
    contexts: [
      { sentenceId: "seed-sentence-0033", meaning: "เลื่อนนัดไปวันหลัง ไม่ใช่ ผลัก และไม่ใช่ git push" },
    ],
    exampleEn: "Can we push it by an hour?",
    exampleTh: "เลื่อนออกไปอีกหนึ่งชั่วโมงได้ไหม",
    exampleSentenceIds: ["seed-sentence-0033"],
    tags: ["meetings", "scheduling"],
    level: "B1",
  },
  {
    id: "seed-vocab-meeting",
    en: "meeting",
    th: "การประชุม",
    pos: "noun",
    transliteration: "kan pra-chum",
    ipa: "/ˈmiːtɪŋ/",
    forms: ["meetings"],
    contexts: [{ sentenceId: "seed-sentence-0033", meaning: "นัดประชุม เป็นคำนาม ไม่ใช่กริยา meet" }],
    exampleEn: "The meeting runs for thirty minutes.",
    exampleTh: "ประชุมใช้เวลาสามสิบนาที",
    exampleSentenceIds: ["seed-sentence-0033"],
    tags: ["meetings"],
    level: "A1",
  },
  {
    id: "seed-vocab-take",
    en: "take",
    th: "รับไปทำ",
    pos: "verb",
    transliteration: "rap pai tham",
    ipa: "/teɪk/",
    forms: ["takes", "took", "taken", "taking"],
    senseNote: "take (accept responsibility for a task)",
    contexts: [
      { sentenceId: "seed-sentence-0034", meaning: "รับงานชิ้นนั้นไปทำ ไม่ได้แปลว่า หยิบ" },
      { sentenceId: "seed-sentence-0035", meaning: "ในวลี take it offline = ยกเรื่องไปคุยกันนอกที่ประชุม" },
    ],
    exampleEn: "I'll take the logging ticket.",
    exampleTh: "ผมขอรับงานเรื่องล็อกไปทำ",
    exampleSentenceIds: ["seed-sentence-0034", "seed-sentence-0035"],
    tags: ["meetings", "work"],
    level: "B1",
  },
  {
    id: "seed-vocab-offline",
    en: "offline",
    th: "นอกที่ประชุม",
    pos: "adverb",
    transliteration: "nok thii pra-chum",
    ipa: "/ˌɒfˈlaɪn/",
    senseNote: "take it offline (continue the discussion outside the meeting)",
    contexts: [
      {
        sentenceId: "seed-sentence-0035",
        meaning: "คุยกันต่อนอกวงประชุม ไม่ได้เกี่ยวกับการตัดอินเทอร์เน็ต",
      },
    ],
    exampleEn: "We took the design debate offline.",
    exampleTh: "เรายกเรื่องเถียงดีไซน์ไปคุยกันข้างนอก",
    exampleSentenceIds: ["seed-sentence-0035"],
    tags: ["meetings"],
    level: "B2",
  },

  // -------------------------------------------------------------- Technical interviews
  {
    id: "seed-vocab-make-sure",
    en: "make sure",
    th: "ทำให้แน่ใจ",
    pos: "phrase",
    transliteration: "tham hai nae chai",
    ipa: "/meɪk ʃʊə(r)/",
    forms: ["sure"],
    contexts: [{ sentenceId: "seed-sentence-0036", meaning: "ตรวจให้แน่ใจก่อนลงมือ ตามด้วยประโยคเต็ม" }],
    exampleEn: "Make sure the tests run locally first.",
    exampleTh: "ตรวจให้แน่ใจก่อนว่าเทสต์รันบนเครื่องได้",
    exampleSentenceIds: ["seed-sentence-0036"],
    tags: ["interviews"],
    level: "B1",
  },
  {
    id: "seed-vocab-understand",
    en: "understand",
    th: "เข้าใจ",
    pos: "verb",
    transliteration: "khao chai",
    ipa: "/ˌʌndəˈstænd/",
    forms: ["understands", "understood", "understanding"],
    contexts: [
      {
        sentenceId: "seed-sentence-0036",
        meaning: "เข้าใจโจทย์ การทวนโจทย์ก่อนเริ่มเป็นสิ่งที่ผู้สัมภาษณ์อยากเห็น",
      },
    ],
    exampleEn: "I want to understand the constraints first.",
    exampleTh: "ผมอยากเข้าใจข้อจำกัดก่อน",
    exampleSentenceIds: ["seed-sentence-0036"],
    tags: ["interviews"],
    level: "A2",
  },
  {
    id: "seed-vocab-assume",
    en: "assume",
    th: "สมมติ",
    pos: "verb",
    transliteration: "som-mut",
    ipa: "/əˈsjuːm/",
    forms: ["assumes", "assumed", "assuming", "assumption", "assumptions"],
    contexts: [{ sentenceId: "seed-sentence-0037", meaning: "ตั้งสมมติฐาน การถามก่อนสมมติแสดงว่าคิดรอบคอบ" }],
    exampleEn: "Can I assume the ids are unique?",
    exampleTh: "ผมสมมติว่าไอดีไม่ซ้ำกันได้ไหม",
    exampleSentenceIds: ["seed-sentence-0037"],
    tags: ["interviews"],
    level: "B1",
  },
  {
    id: "seed-vocab-input",
    en: "input",
    th: "ข้อมูลเข้า / อินพุต",
    pos: "noun",
    transliteration: "kho-mun khao",
    ipa: "/ˈɪnpʊt/",
    forms: ["inputs"],
    contexts: [
      { sentenceId: "seed-sentence-0037", meaning: "ข้อมูลที่ส่งเข้าฟังก์ชัน" },
      { sentenceId: "seed-sentence-0042", meaning: "ข้อมูลเข้าที่อาจว่างเปล่า ซึ่งต้องจัดการเป็นกรณีแรก" },
    ],
    exampleEn: "The input can be up to a million rows.",
    exampleTh: "อินพุตมีได้ถึงหนึ่งล้านแถว",
    exampleSentenceIds: ["seed-sentence-0037", "seed-sentence-0042"],
    tags: ["interviews", "software"],
    level: "A2",
  },
  {
    id: "seed-vocab-approach",
    en: "approach",
    th: "วิธีการ",
    pos: "noun",
    transliteration: "wi-thii kan",
    ipa: "/əˈprəʊtʃ/",
    forms: ["approaches"],
    contexts: [
      { sentenceId: "seed-sentence-0038", meaning: "แนวทางแก้โจทย์ นับได้ จึงต้องมี a หรือ my นำหน้า" },
      { sentenceId: "seed-sentence-0039", meaning: "แนวทางที่เพิ่งอธิบายไป" },
    ],
    exampleEn: "There are two approaches worth comparing.",
    exampleTh: "มีสองวิธีที่น่าเอามาเทียบกัน",
    exampleSentenceIds: ["seed-sentence-0038", "seed-sentence-0039"],
    tags: ["interviews"],
    level: "B1",
  },
  {
    id: "seed-vocab-brute-force",
    en: "brute force",
    th: "วิธีไล่ลองทุกความเป็นไปได้",
    pos: "noun",
    transliteration: "wi-thii lai long",
    ipa: "/bruːt fɔːs/",
    forms: ["brute", "force"],
    contexts: [
      {
        sentenceId: "seed-sentence-0038",
        meaning: "วิธีตรงไปตรงมาที่ลองทุกกรณี ช้าแต่ถูก ใช้เป็นจุดตั้งต้นได้ดี",
      },
    ],
    exampleEn: "Start with brute force, then optimise.",
    exampleTh: "เริ่มจากวิธีไล่ลองก่อน แล้วค่อยปรับให้เร็วขึ้น",
    exampleSentenceIds: ["seed-sentence-0038"],
    tags: ["interviews", "algorithms"],
    level: "B2",
  },
  {
    id: "seed-vocab-linear",
    en: "linear",
    th: "เชิงเส้น",
    pos: "adjective",
    transliteration: "choeng sen",
    ipa: "/ˈlɪniə(r)/",
    senseNote: "linear time (work grows in step with the input size)",
    contexts: [{ sentenceId: "seed-sentence-0039", meaning: "เวลาที่ใช้โตตามขนาดอินพุตแบบหนึ่งต่อหนึ่ง" }],
    exampleEn: "A single pass gives linear time.",
    exampleTh: "วนรอบเดียวก็ได้เวลาเชิงเส้น",
    exampleSentenceIds: ["seed-sentence-0039"],
    tags: ["interviews", "algorithms"],
    level: "B2",
  },
  {
    id: "seed-vocab-run",
    en: "run",
    th: "ทำงาน / ใช้เวลา",
    pos: "verb",
    transliteration: "tham ngan",
    ipa: "/rʌn/",
    forms: ["runs", "ran", "running"],
    senseNote: "run in ... time (of an algorithm)",
    contexts: [
      {
        sentenceId: "seed-sentence-0039",
        meaning: "ในวลี runs in ... time = ใช้เวลาเท่านั้น ไม่ได้แปลว่า วิ่ง",
      },
    ],
    exampleEn: "It runs in constant time.",
    exampleTh: "มันใช้เวลาคงที่",
    exampleSentenceIds: ["seed-sentence-0039"],
    tags: ["interviews", "algorithms"],
    level: "B2",
  },
  {
    id: "seed-vocab-memory",
    en: "memory",
    th: "หน่วยความจำ",
    pos: "noun",
    transliteration: "nuai khwam cham",
    ipa: "/ˈmeməri/",
    contexts: [
      {
        sentenceId: "seed-sentence-0040",
        meaning: "หน่วยความจำที่โปรแกรมใช้ นับไม่ได้ จึงไม่มี a และไม่เติม s",
      },
    ],
    exampleEn: "The cache uses too much memory.",
    exampleTh: "แคชใช้หน่วยความจำมากเกินไป",
    exampleSentenceIds: ["seed-sentence-0040"],
    tags: ["interviews", "software"],
    level: "B1",
  },
  {
    id: "seed-vocab-hash-map",
    en: "hash map",
    th: "แฮชแมป / ตารางแฮช",
    pos: "noun",
    transliteration: "haet-maep",
    ipa: "/hæʃ mæp/",
    forms: ["hash", "hashmap"],
    contexts: [
      { sentenceId: "seed-sentence-0040", meaning: "โครงสร้างข้อมูลที่ค้นหาได้เร็วมากโดยแลกกับหน่วยความจำ" },
    ],
    exampleEn: "A hash map turns the scan into a lookup.",
    exampleTh: "แฮชแมปเปลี่ยนการไล่หาให้กลายเป็นการเปิดตาราง",
    exampleSentenceIds: ["seed-sentence-0040"],
    tags: ["interviews", "algorithms"],
    level: "B2",
  },
  {
    id: "seed-vocab-step-by-step",
    en: "step by step",
    th: "ทีละขั้น",
    pos: "phrase",
    transliteration: "thii la khan",
    ipa: "/step baɪ step/",
    forms: ["step", "steps"],
    contexts: [
      { sentenceId: "seed-sentence-0041", meaning: "ไล่ไปทีละขั้น ไม่ข้าม ช่วยให้ผู้สัมภาษณ์ตามความคิดทัน" },
    ],
    exampleEn: "Let's trace it step by step.",
    exampleTh: "มาไล่ดูทีละขั้นกัน",
    exampleSentenceIds: ["seed-sentence-0041"],
    tags: ["interviews", "explaining"],
    level: "B1",
  },
  {
    id: "seed-vocab-example",
    en: "example",
    th: "ตัวอย่าง",
    pos: "noun",
    transliteration: "tua yang",
    ipa: "/ɪɡˈzɑːmpl/",
    forms: ["examples"],
    contexts: [
      { sentenceId: "seed-sentence-0041", meaning: "ตัวอย่างข้อมูลจริงที่เอามาลองเดินตามอัลกอริทึม" },
    ],
    exampleEn: "Take a small example with three items.",
    exampleTh: "ลองยกตัวอย่างเล็ก ๆ ที่มีสามตัว",
    exampleSentenceIds: ["seed-sentence-0041"],
    tags: ["interviews"],
    level: "A2",
  },
  {
    id: "seed-vocab-handle",
    en: "handle",
    th: "จัดการ / รองรับ",
    pos: "verb",
    transliteration: "chat kan",
    ipa: "/ˈhændl/",
    forms: ["handles", "handled", "handling"],
    contexts: [{ sentenceId: "seed-sentence-0042", meaning: "เขียนโค้ดรองรับกรณีนั้น ไม่ใช่ จับด้ามจับ" }],
    exampleEn: "We don't handle timeouts yet.",
    exampleTh: "เรายังไม่ได้รองรับกรณีหมดเวลา",
    exampleSentenceIds: ["seed-sentence-0042"],
    tags: ["interviews", "software"],
    level: "B1",
  },
  {
    id: "seed-vocab-empty",
    en: "empty",
    th: "ว่างเปล่า",
    pos: "adjective",
    transliteration: "wang plao",
    ipa: "/ˈempti/",
    contexts: [{ sentenceId: "seed-sentence-0042", meaning: "ไม่มีข้อมูลเลย เป็นกรณีที่มักทำให้โค้ดพัง" }],
    exampleEn: "What should an empty list return?",
    exampleTh: "ถ้าลิสต์ว่างควรคืนค่าอะไร",
    exampleSentenceIds: ["seed-sentence-0042"],
    tags: ["interviews", "software"],
    level: "A2",
  },
  {
    id: "seed-vocab-hint",
    en: "hint",
    th: "คำใบ้",
    pos: "noun",
    transliteration: "kham bai",
    ipa: "/hɪnt/",
    forms: ["hints", "hinted"],
    contexts: [
      { sentenceId: "seed-sentence-0043", meaning: "คำใบ้ การขอคำใบ้ไม่ใช่การยอมแพ้ ถ้าขออย่างสุภาพ" },
    ],
    exampleEn: "A small hint would help.",
    exampleTh: "ขอคำใบ้นิดเดียวก็ช่วยได้มาก",
    exampleSentenceIds: ["seed-sentence-0043"],
    tags: ["interviews"],
    level: "B1",
  },
  {
    id: "seed-vocab-stuck",
    en: "stuck",
    th: "ติด / ไปต่อไม่ได้",
    pos: "adjective",
    transliteration: "tit",
    ipa: "/stʌk/",
    contexts: [
      { sentenceId: "seed-sentence-0043", meaning: "คิดต่อไม่ออก ใช้คู่กับ be เสมอ เช่น I am stuck" },
    ],
    exampleEn: "I've been stuck on this for an hour.",
    exampleTh: "ผมติดอยู่ตรงนี้มาชั่วโมงหนึ่งแล้ว",
    exampleSentenceIds: ["seed-sentence-0043"],
    tags: ["interviews", "everyday"],
    level: "B1",
  },
  {
    id: "seed-vocab-backend",
    en: "backend",
    th: "ระบบฝั่งหลังบ้าน",
    pos: "noun",
    transliteration: "fang lang ban",
    ipa: "/ˈbækend/",
    forms: ["back-end", "backends"],
    contexts: [
      { sentenceId: "seed-sentence-0044", meaning: "ฝั่งเซิร์ฟเวอร์และฐานข้อมูล ตรงข้ามกับ frontend" },
    ],
    exampleEn: "I moved from frontend to backend last year.",
    exampleTh: "ปีที่แล้วผมย้ายจากฝั่งหน้าบ้านมาหลังบ้าน",
    exampleSentenceIds: ["seed-sentence-0044"],
    tags: ["interviews", "software"],
    level: "B1",
  },
  {
    id: "seed-vocab-mostly",
    en: "mostly",
    th: "เป็นหลัก / ส่วนใหญ่",
    pos: "adverb",
    transliteration: "pen lak",
    ipa: "/ˈməʊstli/",
    forms: ["most"],
    contexts: [
      {
        sentenceId: "seed-sentence-0044",
        meaning: "ส่วนใหญ่แต่ไม่ทั้งหมด วางหลังกริยาช่วย เช่น have mostly worked",
      },
    ],
    exampleEn: "I mostly write Go these days.",
    exampleTh: "ช่วงนี้ผมเขียน Go เป็นหลัก",
    exampleSentenceIds: ["seed-sentence-0044"],
    tags: ["interviews"],
    level: "B1",
  },
  {
    id: "seed-vocab-day-to-day",
    en: "day to day",
    th: "งานประจำวัน",
    pos: "adjective",
    transliteration: "ngan pra-cham wan",
    ipa: "/deɪ tə deɪ/",
    forms: ["day", "day-to-day", "days"],
    contexts: [
      {
        sentenceId: "seed-sentence-0045",
        meaning: "สิ่งที่ทำเป็นประจำทุกวัน เป็นคำถามที่ดีเวลาผู้สัมภาษณ์เปิดให้ถาม",
      },
    ],
    exampleEn: "What does your day to day involve?",
    exampleTh: "งานประจำวันของคุณมีอะไรบ้าง",
    exampleSentenceIds: ["seed-sentence-0045"],
    tags: ["interviews"],
    level: "B2",
  },
  {
    id: "seed-vocab-team",
    en: "team",
    th: "ทีม",
    pos: "noun",
    transliteration: "thim",
    ipa: "/tiːm/",
    // The sentence says "the team's day to day", so the possessive is what gets tapped.
    forms: ["teams", "team's"],
    contexts: [{ sentenceId: "seed-sentence-0045", meaning: "ทีมที่เรากำลังสัมภาษณ์จะเข้าไปร่วม" }],
    exampleEn: "How big is the team?",
    exampleTh: "ทีมมีกี่คนครับ",
    exampleSentenceIds: ["seed-sentence-0045"],
    tags: ["interviews", "work"],
    level: "A1",
  },

  // ----------------------------------------------------------------- Workplace English
  {
    id: "seed-vocab-take-off",
    en: "take off",
    th: "ลาหยุด",
    pos: "phrase",
    transliteration: "la yut",
    ipa: "/teɪk ɒf/",
    forms: ["off"],
    senseNote: "take a day off (not go to work that day)",
    contexts: [
      {
        sentenceId: "seed-sentence-0046",
        meaning: "ลาหยุดหนึ่งวัน วันที่จะลาแทรกอยู่กลางวลี เช่น take Friday off",
      },
    ],
    exampleEn: "I'm taking Monday off.",
    exampleTh: "ผมจะลาวันจันทร์",
    exampleSentenceIds: ["seed-sentence-0046"],
    tags: ["workplace"],
    level: "A2",
  },
  {
    id: "seed-vocab-friday",
    en: "Friday",
    th: "วันศุกร์",
    pos: "noun",
    transliteration: "wan suk",
    ipa: "/ˈfraɪdeɪ/",
    forms: ["Fridays"],
    contexts: [
      { sentenceId: "seed-sentence-0046", meaning: "ชื่อวันในภาษาอังกฤษขึ้นต้นด้วยตัวพิมพ์ใหญ่เสมอ" },
    ],
    exampleEn: "We release on Friday afternoons.",
    exampleTh: "เราปล่อยรีลีสบ่ายวันศุกร์",
    exampleSentenceIds: ["seed-sentence-0046"],
    tags: ["workplace", "time"],
    level: "A1",
  },
  {
    id: "seed-vocab-attach",
    en: "attach",
    th: "แนบไฟล์",
    pos: "verb",
    transliteration: "naep fai",
    ipa: "/əˈtætʃ/",
    forms: ["attaches", "attached", "attaching", "attachment"],
    contexts: [
      {
        sentenceId: "seed-sentence-0047",
        meaning: "แนบไฟล์มากับอีเมล ใช้ attach A to B รูป -ing บอกว่ากำลังทำในอีเมลฉบับนี้",
      },
    ],
    exampleEn: "I've attached the slides.",
    exampleTh: "ผมแนบสไลด์มาให้แล้ว",
    exampleSentenceIds: ["seed-sentence-0047"],
    tags: ["workplace", "email"],
    level: "B1",
  },
  {
    id: "seed-vocab-report",
    en: "report",
    th: "รายงาน",
    pos: "noun",
    transliteration: "rai ngan",
    ipa: "/rɪˈpɔːt/",
    forms: ["reports", "reported", "reporting"],
    contexts: [{ sentenceId: "seed-sentence-0047", meaning: "เอกสารสรุปผล เป็นคำนามในประโยคนี้" }],
    exampleEn: "The report is two pages long.",
    exampleTh: "รายงานยาวสองหน้า",
    exampleSentenceIds: ["seed-sentence-0047"],
    tags: ["workplace"],
    level: "A2",
  },
  {
    id: "seed-vocab-heads-up",
    en: "heads up",
    th: "การบอกล่วงหน้า",
    pos: "noun",
    transliteration: "kan bok luang na",
    ipa: "/hedz ʌp/",
    forms: ["heads", "heads-up"],
    contexts: [
      {
        sentenceId: "seed-sentence-0048",
        meaning: "การเตือนล่วงหน้า เป็นคำนาม จึงใช้ the heads up ไม่ใช่กริยา",
      },
    ],
    exampleEn: "Thanks for the heads up about the outage.",
    exampleTh: "ขอบคุณที่บอกล่วงหน้าเรื่องระบบล่ม",
    exampleSentenceIds: ["seed-sentence-0048"],
    tags: ["workplace"],
    level: "B1",
  },
  {
    id: "seed-vocab-thanks",
    en: "thanks",
    th: "ขอบคุณ",
    pos: "interjection",
    transliteration: "khop khun",
    ipa: "/θæŋks/",
    forms: ["thank"],
    contexts: [{ sentenceId: "seed-sentence-0048", meaning: "ขอบคุณแบบไม่เป็นทางการ ตามด้วย for แล้วคำนาม" }],
    exampleEn: "Thanks for catching that bug.",
    exampleTh: "ขอบคุณที่เจอบั๊กนั้นนะ",
    exampleSentenceIds: ["seed-sentence-0048"],
    tags: ["workplace", "everyday"],
    level: "A1",
  },
  {
    id: "seed-vocab-work-from-home",
    en: "work from home",
    th: "ทำงานที่บ้าน",
    pos: "phrase",
    transliteration: "tham ngan thii ban",
    ipa: "/wɜːk frəm həʊm/",
    forms: ["home"],
    contexts: [
      {
        sentenceId: "seed-sentence-0049",
        meaning: "ทำงานจากบ้าน ใช้ from ไม่ใช่ at และไม่ต้องมี the นำหน้า home",
      },
    ],
    exampleEn: "I work from home on Wednesdays.",
    exampleTh: "ผมทำงานที่บ้านทุกวันพุธ",
    exampleSentenceIds: ["seed-sentence-0049"],
    tags: ["workplace", "remote"],
    level: "A2",
  },
  {
    id: "seed-vocab-reply",
    en: "reply",
    th: "การตอบกลับ",
    pos: "noun",
    transliteration: "kan top klap",
    ipa: "/rɪˈplaɪ/",
    forms: ["replies", "replied", "replying"],
    contexts: [{ sentenceId: "seed-sentence-0050", meaning: "การตอบอีเมล เป็นคำนามในวลี the slow reply" }],
    exampleEn: "I owe you a reply on that thread.",
    exampleTh: "ผมยังค้างตอบเธรดนั้นอยู่",
    exampleSentenceIds: ["seed-sentence-0050"],
    tags: ["workplace", "email"],
    level: "B1",
  },
  {
    id: "seed-vocab-away",
    en: "away",
    th: "ไม่อยู่",
    pos: "adverb",
    transliteration: "mai yu",
    ipa: "/əˈweɪ/",
    contexts: [{ sentenceId: "seed-sentence-0050", meaning: "ไม่ได้อยู่ทำงาน ใช้คู่กับ be เช่น I was away" }],
    exampleEn: "She's away until the fifth.",
    exampleTh: "เขาไม่อยู่จนถึงวันที่ห้า",
    exampleSentenceIds: ["seed-sentence-0050"],
    tags: ["workplace"],
    level: "B1",
  },
];
